/**
 * NOVA-200（新星计划）· 双语标签表（zh / en）（S0 地基 · AI-01 路代建，十六路共享）。
 *
 * 键规则：
 * - `W-XXX`  → [zh 标题, en 标题]；`W-XXXd` → [zh 描述, en 描述]；
 * - `novaP_*` 参数名；`novaO_*` 选项值；`novaH_*` 新星中枢界面文案。
 * novaT 缺键回退 zh 再回退键名本身。
 */

import type { Lang } from "../../i18n/dictionaries";

export type NovaLabel = [string, string]; // [zh, en]

export const NOVA_LABELS: Record<string, NovaLabel> = {
  // ---- 域1 启动与品牌剧场 ----
  "W-001": ["启动温度制式", "Boot Temperature"],
  "W-001d": ["按电源状态区分点火制式：冷启走熔炉升温、快启走余烬复燃、会话恢复直接进入。", "Ignition regime by power state: furnace on cold boot, ember on fast boot, none on session resume."],
  "W-002": ["启动天气预报", "Boot Forecast"],
  "W-002d": ["启动第 1 秒打出耗时微预报，结束时回写误差，诚实校准不编造。", "One-line duration forecast in the first second; error written back for honest calibration."],
  "W-003": ["跳映启动", "Skip-Start"],
  "W-003d": ["按键只跳过纯视觉段，真实加载如实保留并自报 SKIPPED CINEMATICS ONLY。", "Skips visuals only; real loading kept and honestly reported as SKIPPED CINEMATICS ONLY."],
  "W-004": ["启动声场景感知", "Sound Scene Sense"],
  "W-004d": ["静音环境自动轻响、深夜自动静默改微振视觉，双因子规则明示可关。", "Boot sound adapts to volume and night hours; rules shown and switchable."],
  "W-005": ["多屏顺次点火", "Cascade Ignite"],
  "W-005d": ["扩展屏以 150ms 交错顺次点亮，每屏点亮代表真实挂载完成。", "Extended screens ignite in 150ms stagger, each marking a real mount completion."],
  "W-006": ["启动足迹墙", "Boot Footprints"],
  "W-006d": ["最近 20 次启动每枚一行光点，耗时映射色温，是启动的年轮。", "Last 20 boots as light rows, duration mapped to color temperature — growth rings of booting."],
  "W-007": ["下次启动预览", "Next-Boot Preview"],
  "W-007d": ["关机流程中预演下次启动：自启清单 + 预估时长 + 上次实际值。", "Rehearse the next boot at shutdown: autostart list, estimate and last actual."],
  "W-008": ["品牌星座", "Brand Constellation"],
  "W-008d": ["启动尾声字标化作可交互星座，点星展开本版能力，4 秒后归位。", "Wordmark becomes an interactive constellation; stars reveal this build's abilities."],
  "W-009": ["启动里程碑微音", "Milestone Notes"],
  "W-009d": ["跨过 25/50/75/100% 四个真实里程碑播放上行微音，听进度无障碍。", "Rising notes at the four real milestones — hear your progress."],
  "W-010": ["电源仪式音", "Power Rite Music"],
  "W-010d": ["关机/重启的 1.2s 下行收束告别音，三制式可与谢幕视觉同步。", "A 1.2s descending farewell tone for shutdown, three styles, synced with the curtain."],
  "W-011": ["启动情绪测温", "Exit Mood Thermometer"],
  "W-011d": ["按上次退出方式差异化本次启动：正常/崩溃安抚版/断电检视版。", "Boot mood follows last exit: standard, soothing after crash, inspecting after power loss."],
  "W-012": ["启动源流戳", "Startup Source Stamp"],
  "W-012d": ["桌面就绪后右下角 16px 源流戳：COLD/FAST/RESUME/RECOVER，悬停看判定链。", "A 16px corner stamp COLD/FAST/RESUME/RECOVER with a hover judgment chain."],

  // ---- 域2 窗口与空间 ----
  "W-013": ["窗口质量物理", "Mass Physics"],
  "W-013d": ["窗口面积映射惯性质量：大窗起步沉、停止有余韵，小窗轻快如纸。", "Window area maps inertia mass: big windows feel heavy, small ones paper-light."],
  "W-014": ["磁吸边缘手感", "Magnetic Edge"],
  "W-014d": ["吸附线前 6px 阻尼磁场 + 吸附线呼吸确认，手感前置不改吸附规则。", "A 6px damped field before snap lines with a breathing confirm; feel only, no rule change."],
  "W-015": ["窗口族谱", "Window Genealogy"],
  "W-015d": ["以进程父子树展示窗口诞生关系，点击聚焦、右键结束整树。", "Windows as a parent-child process tree; click to focus, right-click to end a lineage."],
  "W-016": ["Z 序阴影深度", "Z-Shadow"],
  "W-016d": ["z 序映射阴影深度形成空气透视，焦点切换 200ms 平滑过渡。", "Z-order maps shadow depth for aerial perspective, easing over 200ms."],
  "W-017": ["空间气味标记", "Space Scent"],
  "W-017d": ["每虚拟桌面专属色相，切换瞬间辉光闪现 600ms 做空间记忆锚点。", "Each desktop owns a hue; switching flashes a 600ms glow as a spatial anchor."],
  "W-018": ["键盘吸附格阵", "Key Snap Lattice"],
  "W-018d": ["Alt+小键盘 1-9 九宫格直达吸附，连按同格二次恢复原位。", "Alt+Numpad 1-9 snaps to a nine-cell lattice; press again to restore."],
  "W-019": ["几何裁剪", "Geometry Snap-8"],
  "W-019d": ["窗口宽高一键取整 8px 网格并对齐屏幕安全区，消除像素参差。", "Round window sizes to an 8px grid and align to the safe area."],
  "W-020": ["焦点回声", "Focus Echo"],
  "W-020d": ["久未聚焦的上一个焦点窗口任务栏图标呼吸微光召回，至多一枚。", "The last unfocused window breathes softly on the taskbar to be recalled."],
  "W-021": ["马赛克顾问", "Mosaic Advisor"],
  "W-021d": ["同屏 ≥3 窗且拥挤时按宽高比推荐镶嵌布局，一键应用或忽略。", "Suggests aspect-aware mosaic layouts when 3+ windows crowd the screen."],
  "W-022": ["窗口记忆仓位", "Position Slots"],
  "W-022d": ["每窗口记最近 3 个几何仓位，标题栏菜单一键回滚。", "Each window keeps 3 geometry slots, rollback from the title menu."],
  "W-023": ["轨道浮窗", "Rail Window"],
  "W-023d": ["拖入顶部轨道区变 72px 贴轨浮窗，横向自由滑动，可脱离。", "Drop a window on the top rail to dock it as a 72px floating strip."],
  "W-024": ["空间折叠带", "Fold Ribbon"],
  "W-024d": ["Ctrl+双击桌面空白：非焦点窗折叠为右缘 36px 竖带，零进程干预。", "Ctrl+double-click folds unfocused windows into a 36px edge ribbon."],
  "W-025": ["窗口标签", "Window Labels"],
  "W-025d": ["给窗口贴浮动文字标签，随窗口移动，Alt+Tab 中显示，≤12 字。", "Attach floating text labels to windows; shown in Alt+Tab."],

  // ---- 域3 桌面设计与图标 ----
  "W-026": ["图标星座排列", "Constellation Layout"],
  "W-026d": ["第五种排列：沿 6 条真实星座曲线布图标并以细线连成星图。", "A fifth layout: icons along six real constellations with faint star lines."],
  "W-027": ["图标养成", "Icon Growth"],
  "W-027d": ["高频图标存在感生长，30 天未点渐入半休眠，交互即唤醒。", "Icons grow presence with use and semi-hibernate after 30 idle days."],
  "W-028": ["季节地影", "Seasonal Ground"],
  "W-028d": ["接触阴影随四季微调色温（春粉/夏白/秋棕/冬蓝），南半球反转。", "Contact shadows shift hue by season, inverted for the southern hemisphere."],
  "W-029": ["图标排行榜", "Icon Leaderboard"],
  "W-029d": ["本月点击 Top10 领奖台 + 沉睡王，游戏化的桌面榜单。", "Monthly top-10 icon podium plus a sleep king — a gamified board."],
  "W-030": ["桌面午憩", "Desk Siesta"],
  "W-030d": ["10 分钟无输入图标层进入午憩态，任一输入即刻全醒。", "After 10 idle minutes the icon layer rests; any input wakes it."],
  "W-031": ["图标老化公约", "Icon Aging"],
  "W-031d": ["7/30 天老化梯度 + 一次性退休提案，拒绝后 90 天免疫。", "7/30-day aging gradient with a one-time retirement proposal."],
  "W-032": ["桌面地平线", "Desktop Floor"],
  "W-032d": ["图标基线 2px 微光地平线，随壁纸取色，增强秩序感。", "A 2px glowing horizon under the icons, tinted from the wallpaper."],
  "W-033": ["布局合影", "Layout Photo"],
  "W-033d": ["给布局拍视觉快照入相册，历史合影一键差异对比还原。", "Snapshot layouts into an album; restore with a diff preview."],
  "W-034": ["图标层光雪", "Icon Snowfall"],
  "W-034d": ["图标层专属微光飘雪，仅晚间自动开启，与壁纸粒子独立。", "A dedicated 2px snowfall over icons at night, independent of wallpaper."],
  "W-035": ["声音地形", "Panned Clicks"],
  "W-035d": ["图标点击微音按 X 坐标声像定位，用听觉强化空间感。", "Icon clicks pan left/right by X position — audio topology."],
  "W-036": ["图标结组", "Icon Clusters"],
  "W-036d": ["框选 ≥2 图标按 G 临时结组，整体移动开合，会话级组织。", "Box-select and press G to cluster icons for this session."],
  "W-037": ["桌面标尺模式", "Spacing Ruler"],
  "W-037d": ["拖图标按住 R 显示与最近邻的像素距离标尺，网格吸附时标 SNAP。", "Hold R while dragging to see neighbor-distance rulers and SNAP badges."],
  "W-038": ["原点坐标", "Home Position"],
  "W-038d": ["每枚图标记住首次落点，一键全体回原点或个体归位。", "Icons remember their first drop point; return all or one to origin."],

  // ---- 域4 任务栏与开始菜单 ----
  "W-039": ["任务栏磁漂", "Gravity Dock"],
  "W-039d": ["鼠标进入任务栏，图标以 4px 幅度向指针群体磁漂，离开回位。", "Taskbar icons gravitate 4px toward the pointer and spring back."],
  "W-040": ["开始菜单角色预设", "Persona Layouts"],
  "W-040d": ["开发者/创作者/学生三预设一键切换，可改后另存。", "Developer / creator / student start-menu presets, editable and savable."],
  "W-041": ["任务栏潮汐条", "Tidal Bar"],
  "W-041d": ["图标占用率驱动栏体潮汐：宽松 +6px、紧凑 -4px，500ms 缓动。", "The dock breathes with occupancy: +6px loose, -4px dense, eased 500ms."],
  "W-042": ["零点击详情卡", "Zero-Click Card"],
  "W-042d": ["搜索命中首项直接展开详情卡：版本/上次启动/最近文件。", "The first search hit shows a detail card before you click."],
  "W-043": ["任务栏时间戳微史", "Taskbar Timeline"],
  "W-043d": ["悬停栏空白 800ms 浮出 30 分钟刻度的今日活动微时间线。", "Hover the empty dock for a 30-min-granularity today timeline."],
  "W-044": ["悬停窗景预览", "Hover Peek"],
  "W-044d": ["悬停运行图标 500ms 弹出全部窗口实时微缩景，各带关闭钮。", "Hover a running icon for live mini-previews of all its windows."],
  "W-045": ["任务栏模块槽", "Dock Modules"],
  "W-045d": ["两端各 2 模块槽，时钟/律动条/风向标等可拔插互换。", "Two module slots at each end; indicators become pluggable modules."],
  "W-046": ["开始菜单昨日区", "Yesterday Zone"],
  "W-046d": ["推荐区新增「昨日用过」差集分区，启动后实时收缩。", "A 'used yesterday' zone that shrinks as you launch today."],
  "W-047": ["任务栏锋锐模式", "Compact Dock"],
  "W-047d": ["32px 图标 + 2px 间距 + 精简时钟的极限密度制式。", "A 32px ultra-compact dock mode with a minimal clock."],
  "W-048": ["启动弹道", "Launch Arc"],
  "W-048d": ["启动应用时光点沿图标→屏心抛物线飞出 240ms，方向仪式。", "A light dot arcs from the icon toward screen center in 240ms."],
  "W-049": ["手柄友好菜单", "Gamepad Menu"],
  "W-049d": ["蓝牙手柄接入自动切手柄布局：瓷砖 1.4× 与 ABXY 导航。", "Bluetooth gamepad auto-switches to a 1.4× tile layout with ABXY nav."],
  "W-050": ["多屏任务栏镜像", "Mirror Taskbar"],
  "W-050d": ["每块屏显示相同钉选与运行图标的镜像栏，同步 ≤100ms。", "Optional mirrored taskbars on every screen, synced within 100ms."],

  // ---- 域5 键盘与输入手感 ----
  "W-051": ["分应用输入节奏记忆", "Pace Memory"],
  "W-051d": ["各应用独立按键重复曲线，按历史间隔中位数自动校准。", "Per-app key-repeat curves calibrated from median input gaps."],
  "W-052": ["Shift 大写覆盖", "Shift Caps Override"],
  "W-052d": ["按住 Shift 临时反转 Caps 状态的物理修正键，松开恢复。", "Holding Shift inverts Caps temporarily; release restores."],
  "W-053": ["输入节奏器", "Rhythm Trainer"],
  "W-053d": ["30s 击键间隔可视化训练与稳定性得分，数据即焚。", "A 30s typing-rhythm trainer with a stability score; nothing kept."],
  "W-054": ["按键长按池", "Long-Press Pool"],
  "W-054d": ["长按 ./、/; 弹出标点池径向环，滚轮或方向选择。", "Long-press ./、/; for radial punctuation pools."],
  "W-055": ["本地短语暖场", "Phrase Warm-up"],
  "W-055d": ["输入框获焦浮出 3 条本地高频短语幽灵建议，Tab 采纳。", "Up to 3 ghost phrase suggestions from local history; Tab to take."],
  "W-056": ["键盘沙坑", "Key Trainer"],
  "W-056d": ["F1 长按反查任意组合的真实绑定，未绑定给 FREE 入口。", "Hold F1 to reverse-lookup any combo's real binding."],
  "W-057": ["打字速度光环", "Speed Aura"],
  "W-057d": ["输入速度映射输入框外圈光环：60WPM 暖亮、30 稳态、低缓呼吸。", "A ring around the input reflects WPM: warm, steady, or resting."],
  "W-058": ["高手时刻", "WPM Moment"],
  "W-058d": ["30s 均速首破 80/100/120 WPM 绽放微型彩带，各一次。", "First time crossing 80/100/120 WPM fires a tiny confetti, once each."],
  "W-059": ["走神暂停印", "Flow Recall"],
  "W-059d": ["输入流中断 3s，任务栏一枚光点做 1.5s 呼吸召回印。", "A 3s typing gap leaves one breathing recall dot on the dock."],
  "W-060": ["剪贴板环槽", "Clip Slots"],
  "W-060d": ["Ctrl+Shift+1/2/3 存入三格热剪贴板，Ctrl+Alt+1/2/3 直取。", "Three explicit clip slots: store and paste by number."],
  "W-061": ["长句呼吸输入", "Marathon Typing Care"],
  "W-061d": ["连续 300 字无停顿浮呼吸气泡提醒，每小时至多 3 次。", "A breathing bubble after 300 continuous characters, ≤3 per hour."],
  "W-062": ["指频热区图", "Zone Heatmap"],
  "W-062d": ["手部 10 分区击键负载热图与月度对比，数据可清零。", "A 10-zone hand-load heatmap with monthly comparison."],
  "W-063": ["标点智断", "Smart Punct"],
  "W-063d": ["中文语境句末英文点自动转句号，URL 数字场景豁免。", "Converts trailing ASCII periods in Chinese context; URLs exempt."],

  // ---- 域6 文件与数据能力 ----
  "W-064": ["文件脉搏", "File Pulse"],
  "W-064d": ["写入中文件 2s 脉搏微光，停止 5s 后脉息，一眼识别活文件。", "Files being written pulse every 2s; the pulse rests 5s after."],
  "W-065": ["目录人口普查", "Census Report"],
  "W-065d": ["类型构成饼图 + Top5 + 平均年龄 + 极值，一页摸底报告。", "A one-page census: type pie, top 5, average age, extremes."],
  "W-066": ["借阅书架", "Borrow Shelf"],
  "W-066d": ["拖文件上架=借出记录来源，归还回原位，逾期淡化为红色。", "Borrow files onto a shelf; return moves them home, overdue fades red."],
  "W-067": ["文件墨阶", "Size Ink"],
  "W-067d": ["文件名加粗随体量分级加深，巨石文件附微图标。", "Filename weight deepens with size; boulders get a badge."],
  "W-068": ["目录增长预报", "Growth Forecast"],
  "W-068d": ["30 天增长外推预报红色水位日期，历史与预报同图诚实显示。", "Extrapolates 30-day growth and the red-line date, with honest confidence."],
  "W-069": ["文件迁途志", "Move Journal"],
  "W-069d": ["环境内移动/重命名记录轨迹链，90 天滚动可溯源。", "A 90-day journal of in-app moves and renames per file."],
  "W-070": ["标签代数", "Tag Algebra"],
  "W-070d": ["标签交/并/差组合保存为代数文件夹，实时物化结果。", "Save tag set-algebra queries as live algebra folders."],
  "W-071": ["预览幽灵页", "Ghost Page"],
  "W-071d": ["长文档末页后的 12% 透明幽灵页，暗示内容到此为止。", "A faint ghost page after the last page — nothing more to scroll."],
  "W-072": ["传输律动声", "Transfer Groove"],
  "W-072d": ["传输速率联动环境律动，完成终止和弦，失败不和谐音。", "Transfer speed drives a groove; success chords, failure dissonance."],
  "W-073": ["子夜更钟", "Midnight Delta"],
  "W-073d": ["每日 00:00 一张 3s 更钟卡：今日数据增量一目了然。", "A 3s midnight card summarizing the day's data delta."],
  "W-074": ["目录季节环", "Season Ring"],
  "W-074d": ["12 扇区环形图展示全年文件创建月分布，可按月过滤。", "A 12-sector ring of when this folder's files were born."],
  "W-075": ["回收站出身簿", "Bin Provenance"],
  "W-075d": ["回收站每项附删除方应用 + 原路径 + 入站时间。", "Every bin item shows its deleter, origin path and time."],
  "W-076": ["近踪动港", "Recent Haven"],
  "W-076d": ["最近 5 个真实浏览目录自动浮列，一周未访淡出。", "The five recently browsed folders float up and fade after a week."],

  // ---- 域7 效率与工具中枢 ----
  "W-077": ["时间块雕塑家", "Time Boxing"],
  "W-077d": ["今日时间轴上拖刻 15min 吸附时间块，到点联动专注氛围。", "Sculpt your day in 15-min blocks; blocks trigger focus ambience."],
  "W-078": ["微清单", "Micro Checklist"],
  "W-078d": ["任务栏 3 条微字要务带，完成划线消散，满载折叠计数。", "Three micro todos on the dock; done items strike through."],
  "W-079": ["屏幕时辰簿", "Eye Book"],
  "W-079d": ["每 45min 注视提醒 20-20-20 眨眼，每 4 轮盖一章。", "Every 45 minutes an eye-care nudge; four rounds stamp the book."],
  "W-080": ["多工具横桌", "Tool Table"],
  "W-080d": ["计算器/换算/便签/取色 2×2 并排同屏的聚合桌面。", "Calc + convert + notes + picker side by side in a 2×2 table."],
  "W-081": ["今日收官仪式", "Daily Debrief"],
  "W-081d": ["晚间复盘卡：今日完成 / 未竟 3 条提名明日 / 明日日程前 3。", "An evening debrief card: done, next-3 nominees, tomorrow's top 3."],
  "W-082": ["习惯配比镜", "Habit Ratio"],
  "W-082d": ["近 7 天鼠键操作占比环 + 偏差色带 + 可解释建议。", "A 7-day mouse/keyboard ratio ring with explainable tips."],
  "W-083": ["跨工具超拖", "CrossDrop"],
  "W-083d": ["文件拖到工具图标按类型语义调用：图片取色、文本计数。", "Drop files onto tools: images to picker, text to counter."],
  "W-084": ["会议快车道", "Meeting Lane"],
  "W-084d": ["会议临前一键会议态：麦克风测试/勿扰/保持唤醒/摄像头自检。", "One tap to meeting mode: mic check, DND, stay awake, cam test."],
  "W-085": ["时间梭笔", "Timeline Shuttle"],
  "W-085d": ["以当前时刻为锚回看昨日此时的应用活跃与截图缩略。", "Shuttle to yesterday's same hour for activity and thumbnails."],
  "W-086": ["语音图钉", "Voice Pin"],
  "W-086d": ["F8 长按 10s 说话松开转文字钉到便签区，全程离线。", "Hold F8 to speak up to 10s; offline speech becomes a pinned note."],
  "W-087": ["算术选中", "Snippet Math"],
  "W-087d": ["选中数字 Ctrl+Shift+= 就地运算，结果替换或复制。", "Select numbers and calculate in place; replace or copy."],
  "W-088": ["双栏交换座", "Swap Panes"],
  "W-088d": ["双栏路径与视图状态一键互换，含滚动与选中态。", "Swap dual panes instantly, scroll and selection included."],
  "W-089": ["氛围备忘板", "Ambient Scratch"],
  "W-089d": ["F9 呼出 15 分钟自焚备忘板，纯内存不落盘。", "F9 opens a 15-minute self-burning scratch pad, memory only."],

  // ---- 域8 系统集成与硬件 ----
  "W-090": ["CPU 潮汐壁纸", "CPU Tide"],
  "W-090d": ["CPU 负载映射壁纸粒子潮汐密度，轻载退潮重载涨潮。", "CPU load drives wallpaper particle tides — ebb and surge."],
  "W-091": ["电池健康叙事", "Battery Story"],
  "W-091d": ["电池月度故事卡：循环数/健康趋势/一句人话结论 + 建议。", "A monthly battery story card with plain-language conclusions."],
  "W-092": ["麦克风风铃", "Mic Chime"],
  "W-092d": ["麦克风启用瞬间一声 120ms 木质风铃，与指示灯双通道。", "A 120ms wooden chime the moment the mic activates."],
  "W-093": ["内存川流带", "RAM Stream"],
  "W-093d": ["任务栏顶端 1px 川流光带映射内存流速与亮度。", "A 1px stream on the dock flows with memory pressure."],
  "W-094": ["核心合唱", "Core Chorus"],
  "W-094d": ["每核心一枚 4px 波形柱并列如合唱谱，点击展开 60s 时间线。", "Per-core 4px wave bars like a chorus score, 60s timeline on click."],
  "W-095": ["磁盘巡逻灯", "Disk LED"],
  "W-095d": ["每物理盘一枚读写巡逻微闪灯，闪频限流 4Hz。", "A patrol LED per drive blinks on activity, capped at 4Hz."],
  "W-096": ["电流仪式", "Bolt Ritual"],
  "W-096d": ["插电瞬间 200ms 落雷微光，拔出反向细流，三制式提示音。", "Plug-in fires a 200ms bolt glow; unplug a reverse trickle."],
  "W-097": ["屏幕工时簿", "Panel Hours"],
  "W-097d": ["每屏独立点亮工时账本 + OLED 烧屏风险提示。", "Per-display hour ledger with OLED burn-in advice."],
  "W-098": ["风扇声纹补偿", "Fan Compensate"],
  "W-098d": ["风扇高速时提示音 +6dB 高频穿透补偿，夜间不补偿。", "Boosts alert treble +6dB under fan roar; never at night."],
  "W-099": ["USB 电流印", "Current Print"],
  "W-099d": ["USB 卡片追加协商/实际电流读数，识别吃电大户。", "USB cards gain negotiated/actual current to spot power hogs."],
  "W-100": ["硬件生日书", "Hardware Birthday"],
  "W-100d": ["装机纪念日的蛋糕微标 + 该硬件健康一句话。", "Install anniversaries earn a cake badge and a health line."],
  "W-101": ["环境分贝伴飞", "Decibel Companion"],
  "W-101d": ["环境声级秒级推算，嘈杂提升通知音量，安静微降媒体。", "Ambient dB adapts volumes: louder alerts in noise, softer media in hush."],

  // ---- 域9 兼容性防线 ----
  "W-102": ["应用观察期", "App Watch"],
  "W-102d": ["新应用 48h 观察簿记录崩溃无响应，期满出三级体检小结。", "New apps get a 48h watch log and a three-grade checkup."],
  "W-103": ["DLL 预言者", "DLL Prophet"],
  "W-103d": ["启动前 200ms 快扫导入表，缺 DLL 先弹预言卡再启动。", "Scans imports pre-launch; missing DLLs get a prophecy card first."],
  "W-104": ["全屏逃生演练", "Escape Drill"],
  "W-104d": ["全屏卡死浮现逃生门，三档安全序列绝不波及其它进程。", "A frozen fullscreen app gets an escape hatch with a safe 3-step drill."],
  "W-105": ["输入组段接力", "IME Relay"],
  "W-105d": ["检测组段被吞特征并自动接力重放，白名单制防误伤。", "Detects swallowed IME compositions and replays them, whitelist only."],
  "W-106": ["字体替身", "Font Understudy"],
  "W-106d": ["缺失字体自动匹配 metric 相似替身并浮标提示。", "Missing fonts are recast with metric-similar understudies."],
  "W-107": ["DPI 转场防腐", "DPI Morph"],
  "W-107d": ["DPI 变更瞬间冻结截图 300ms 盖窗防糊，重绘完揭幕。", "Freezes a snapshot for 300ms across DPI changes to hide blur."],
  "W-108": ["遗留应用医院", "Legacy Hospital"],
  "W-108d": ["遗留应用三查三治诊疗流程，处方 20+ 可逐一撤销。", "A clinic for legacy apps: three checks, three cures, reversible."],
  "W-109": ["游戏反作弊礼让", "Anti-Cheat Yield"],
  "W-109d": ["检测反作弊驱动即暂停全部钩子悬浮层，退出 30s 后恢复。", "Suspends all hooks/overlays while anti-cheat runs; resumes after 30s."],
  "W-110": ["蓝屏检尸官", "BSOD Forensics"],
  "W-110d": ["蓝屏后读取 minidump 出中立检尸卡，解析不了如实声明。", "Reads minidumps into neutral forensics cards; INSUFFICIENT DATA if not."],
  "W-111": ["色彩模式转影", "Color Morph"],
  "W-111d": ["HDR↔SDR 或深浅切换叠加 2s 色彩插值转影，零白闪。", "A 2s color-space morph across HDR/SDR and theme flips, zero flashes."],
  "W-112": ["同名实例仲裁", "GPU Arbitration"],
  "W-112d": ["双实例争抢 GPU 弹仲裁卡建议限帧/分核，用户确认才执行。", "Suggests frame caps or affinity when twins fight over the GPU."],
  "W-113": ["系统更新护城河", "Update Moat"],
  "W-113d": ["大版本更新前备份可能失效的环境设置并给回滚指引。", "Backs up at-risk settings before OS updates, with rollback guides."],

  // ---- 域10 安全与隐私 ----
  "W-114": ["隐私体检报告", "Privacy Checkup"],
  "W-114d": ["季度三轴体检：权限漂移/敏感访问/使用趋势，红黄绿总评。", "A quarterly privacy checkup: drift, access, trends; RAG scored."],
  "W-115": ["密码力度合奏", "Strength Ensemble"],
  "W-115d": ["密码框三轨力度条：长度/多样性/模式性，给具体指导。", "A three-track strength meter with concrete advice; no content stored."],
  "W-116": ["摄像头眼罩", "Cam Blindfold"],
  "W-116d": ["双击摄像头图标戴眼罩并显示已蒙眼徽标，再击揭罩。", "Double-click the camera icon to blindfold it with a badge."],
  "W-117": ["敏感文件气泡", "Access Bubble"],
  "W-117d": ["敏感目录文件被访问当下浮 2s 气泡，实时微型告示。", "A 2s bubble the instant a sensitive file is read."],
  "W-118": ["阅后即焚剪贴板", "Burn After Read"],
  "W-118d": ["显式标记剪贴板阅后即焚：粘贴一次自动焚毁或 60s 超时。", "Mark clips to burn after one paste, or 60s timeout."],
  "W-119": ["后台心跳墙", "BG Pulse Wall"],
  "W-119d": ["后台应用各一枚三电平心跳行，一眼看穿谁在偷偷干活。", "Each background app gets a three-level pulse row."],
  "W-120": ["信任衰减曲线", "Trust Decay"],
  "W-120d": ["插件信任分随时间/事件透明衰减，跌破阈值建议复审。", "Plugin trust decays transparently; below threshold a review is advised."],
  "W-121": ["隐私剧场排演", "Privacy Rehearsal"],
  "W-121d": ["沙盒化泄露场景剧场演示，看懂风险机制，零真实数据。", "A sandboxed leak drama that teaches risk with zero real data."],
  "W-122": ["DNS 白话簿", "DNS Ledger"],
  "W-122d": ["DNS 请求白话账本：域名标注用途，可疑未标注红标。", "A plain-language ledger of DNS lookups, suspects flagged red."],
  "W-123": ["指纹黑匣", "Fingerprint Vault"],
  "W-123d": ["使用特征单向哈希黑匣，换机比对手感，默认关闭。", "A one-way usage fingerprint for migration likeness; opt-in."],
  "W-124": ["安全红线通知", "Sec Alert Line"],
  "W-124d": ["安全事件通知金边红字置顶，不受合流与勿扰消音。", "Security notices wear gold-on-red and bypass DND muting."],
  "W-125": ["权限族谱", "Perm Genealogy"],
  "W-125d": ["文件 ACL 继承链可视化，异常继承红标，FAT32 如实隐藏。", "Visualizes ACL inheritance chains; flags anomalies, hides on FAT32."],
  "W-126": ["焚毁仪式", "Burn Ritual"],
  "W-126d": ["销毁动作 1.2s 蓄力显示清单，点火粒子焚毁防手滑。", "Destruction requires a 1.2s charged ritual with a content list."],

  // ---- 域11 开放生态 ----
  "W-127": ["插件基因编辑", "Plugin Genes"],
  "W-127d": ["插件能力基因逐项开关矩阵，关基因得到明确拒绝。", "Per-gene capability switches for plugins; disabled genes reject loudly."],
  "W-128": ["生态雷达图", "Eco Radar"],
  "W-128d": ["插件数/主题数/活跃度/更新/安全/贡献六轴生态雷达。", "A six-axis radar of ecosystem health with monthly overlay."],
  "W-129": ["社区声邮", "Voice Post"],
  "W-129d": ["离线起草反馈声邮，知情手动批量投递，默认零网络。", "Draft feedback offline and post it knowingly; zero network by default."],
  "W-130": ["依赖树医生", "Dep Doctor"],
  "W-130d": ["依赖冲突树 + 三种解法影响面预估的门诊部。", "A clinic for dependency conflicts with three remedy estimates."],
  "W-131": ["本地灯塔", "Plugin Lighthouse"],
  "W-131d": ["已装插件 CPU/内存/拖累/事件四维实测跑分。", "Local four-dimension benchmarks for installed plugins."],
  "W-132": ["二维码驿传", "QR Relay"],
  "W-132d": ["配置打包为本地二维码序列跨机对传，零网络零云。", "Ship settings as QR sequences across machines, no network."],
  "W-133": ["限流列车", "Rate Train"],
  "W-133d": ["网关限流配额以车厢载客呈现，超载车厢红色。", "Gateway quotas as train cars; overloaded cars glow red."],
  "W-134": ["权限语言墙", "Perm Decoder"],
  "W-134d": ["插件权限声明白话翻译墙 + 风险分级色标。", "Permission names decoded into plain words with risk colors."],
  "W-135": ["主题换器官预览", "Theme Surgery"],
  "W-135d": ["主题应用前逐 token diff，可逐器官勾选采纳。", "Preview theme token diffs and adopt them organ by organ."],
  "W-136": ["市场策展货架", "Curator Shelf"],
  "W-136d": ["官方策展与社区热度双货架并列，可按体检分过滤。", "Curated and community shelves side by side, filterable by score."],
  "W-137": ["行为剧作 replay", "Sandbox Replay"],
  "W-137d": ["沙盒试用行为录成剧本逐动作回放再审。", "Sandbox trials become replayable scripts for review."],
  "W-138": ["插件讣告", "Plugin Obituary"],
  "W-138d": ["卸载插件的服务叙事告别页：服役多久/完成几次。", "A fond farewell page summarizing a plugin's service."],

  // ---- 域12 视觉、个性化与氛围 ----
  "W-139": ["桌面极光历", "Aurora Calendar"],
  "W-139d": ["极光色相随周序 15° 巡回，一年绕一圈，把时间织进光里。", "Aurora hue drifts 15° weekly — a year-long loop woven into light."],
  "W-140": ["壁纸生态位", "Wallpaper Niche"],
  "W-140d": ["壁纸钟爱/休眠/荣休三态生命周期，轮换只从钟爱池抽取。", "Wallpapers live in loved/dormant/retired niches; rotation draws the loved."],
  "W-141": ["壁纸水族馆", "Wallpaper Aquarium"],
  "W-141d": ["粒子获得自主行为：游动避让光标群体聚散，活的生态系。", "Particles swim, dodge the cursor and flock — a living diorama."],
  "W-142": ["图标美术馆", "Icon Gallery"],
  "W-142d": ["图标以 64px 大卡排布成展览墙的鉴赏视图。", "Icons hang as 64px gallery cards for appreciation."],
  "W-143": ["材质季节纹理", "Material Season"],
  "W-143d": ["材质随季节呼吸：春季纤维感 +8%、冬季磨砂感 +10%。", "Materials breathe with seasons: fibrous spring, frosted winter."],
  "W-144": ["光标光笔", "Light Pen"],
  "W-144d": ["光标 24px 静态伴飞柔光晕，深色界面定位性更佳。", "A 24px halo rides the cursor for dark-UI legibility."],
  "W-145": ["壁纸声纹配对", "Wallpaper Soundprint"],
  "W-145d": ["每张壁纸推荐声纹，视觉听觉成套选择，无推荐如实显示。", "Wallpapers come with soundprint pairs; NO MATCH when none."],
  "W-146": ["主题香水卡", "Theme Scent"],
  "W-146d": ["主题的嗅觉签名隐喻卡：闻起来像雪松还是海盐。", "A scent card per theme — cedar, sea salt, old books."],
  "W-147": ["视觉噪声计", "Visual Noise Meter"],
  "W-147d": ["活跃动效层数计量条 + 一键安静档全部降 50%。", "Counts active motion layers; one tap halves them all."],
  "W-148": ["像素画模式", "Pixel Mode"],
  "W-148d": ["720p 降采样最近邻放大的像素画制式，怀旧换装。", "720p nearest-neighbor pixel mode for a retro outfit."],
  "W-149": ["暗角画框", "Frame Mode"],
  "W-149d": ["屏幕四缘六制式装饰画框，全屏应用自动隐框。", "Six decorative frame styles; fullscreen apps hide them."],
  "W-150": ["长曝光壁纸", "Long Exposure"],
  "W-150d": ["每小时采样主色，一年 8760 帧合成时间色带。", "Hourly color samples weave a year-long exposure ribbon."],
  "W-151": ["月光舞台", "Moonlight Stage"],
  "W-151d": ["真实月相映射环境月光层，阴晴圆缺成为光的节律。", "Real moon phases set the ambient moonlight layer."],

  // ---- 域13 声音与通知 ----
  "W-152": ["声纹博物馆", "Soundprint Museum"],
  "W-152d": ["3 分钟导览全部系统音，逐个播放就地改音。", "A 3-minute tour of every system sound, editable in place."],
  "W-153": ["通知时间热图", "Notify Heatmap"],
  "W-153d": ["7×24 热图显示通知密度，点击热格查看历史。", "A 7×24 heatmap of notification pressure."],
  "W-154": ["晨间电台", "Morning Radio"],
  "W-154d": ["首解锁 90s 本地 TTS 播报日程/待办/昨日摘要，可跳过。", "A 90s local TTS briefing after first unlock; skippable."],
  "W-155": ["双耳平衡罗盘", "Stereo Compass"],
  "W-155d": ["左右声道测试与声像定位小测，生成 ±3dB 温和补偿。", "Stereo tests yield a gentle ±3dB personal balance."],
  "W-156": ["勿扰雨滴", "DND Raindrop"],
  "W-156d": ["勿扰期通知转一声轻雨滴，视觉零弹出，可静雨。", "During DND each notice lands as one soft raindrop."],
  "W-157": ["音量晨昏曲线", "Volume Circadian"],
  "W-157d": ["全局音量晨昏自动微调，手动调整 2h 内曲线让位。", "Volume follows the sun; manual tweaks win for 2 hours."],
  "W-158": ["工作整点钟声", "Session Chime"],
  "W-158d": ["专注会话跨整点一声 200ms 软钟声，每小时至多一声。", "A soft chime when a work session crosses the hour."],
  "W-159": ["勿扰触觉回声", "Haptic Echo"],
  "W-159d": ["勿扰期通知令栏体轻颤一次的知觉残留。", "DND notices make the dock shiver once — a haptic echo."],
  "W-160": ["声纹钢琴", "Sound Piano"],
  "W-160d": ["12 键试奏键盘 auditioning 候选系统音。", "A 12-key piano for auditioning system sounds."],
  "W-161": ["声纹历史", "Echo History"],
  "W-161d": ["最近 3 次系统声微史与一键重播。", "The last three system sounds, replayable."],
  "W-162": ["通知队列聚光", "Queue Spotlight"],
  "W-162d": ["多条通知逐条聚光上演，其余暗处计数。", "Queued notices take the spotlight one by one."],
  "W-163": ["声纹和声分", "Harmony Score"],
  "W-163d": ["并发声频段冲突自动 60ms 微错峰，声音的美学纪律。", "Overlapping tones stagger 60ms to keep the harmony."],

  // ---- 域14 无障碍与本地化 ----
  "W-164": ["声令官", "Voice Commander"],
  "W-164d": ["20 条封闭语法离线声令，按住 Ctrl+Alt+V 说话。", "Twenty closed-grammar offline voice commands; opt-in."],
  "W-165": ["放大重锤", "Layout Zoom"],
  "W-165d": ["150% 布局级重排放大，文字图标控件连网格一起缩放。", "A 150% layout-level zoom that reflows, not blurs."],
  "W-166": ["色觉配方改写", "Palette Rewrite"],
  "W-166d": ["三型色觉自测后改写主题色板源配方，非滤镜叠加。", "Rewrites the palette source after a color-vision self-test."],
  "W-167": ["听障听诊器", "Deaf Channel"],
  "W-167d": ["任一系统声可转屏幕缘闪光/栏脉冲/标题闪动三通道。", "Every sound can flash edges, pulse the dock or blink titles."],
  "W-168": ["长者大卡", "Elder Cards"],
  "W-168d": ["1.3× 大卡 + 双确认 + 每日微教程的适老套装。", "An elder mode: 1.3× cards, double confirms, daily lessons."],
  "W-169": ["语法温柔墙", "Grammar Wall"],
  "W-169d": ["失焦时本地语法检查以温柔下划线建议，不自动改写。", "Gentle underline suggestions after blur; never auto-rewrites."],
  "W-170": ["数字报数", "Number Voice"],
  "W-170d": ["金额逐位/日期完整/电话分节三制式 TTS 报数。", "TTS reads amounts, dates and phones in three protocols."],
  "W-171": ["左右手镜像", "Hand Mirror"],
  "W-171d": ["整套键位中心对称翻转生成镜像方案入库。", "Mirrors the whole keymap for one-handed use."],
  "W-172": ["字体栈医生", "Font Doctor"],
  "W-172d": ["字体栈逐级体检 + 缺字扫描 + 修复建议。", "A stack-level font checkup with repair advice."],
  "W-173": ["零术语词典", "Jargon Decoder"],
  "W-173d": ["悬停按 Ctrl+Alt+D 弹白话术语卡 300 条。", "Ctrl+Alt+D explains any jargon in plain words."],
  "W-174": ["拼音北极星", "Pinyin Star"],
  "W-174d": ["界面中文附拼音上标 + 悬停本地朗读。", "Pinyin superscripts over UI text with hover speech."],
  "W-175": ["盲文徽章", "Braille Badge"],
  "W-175d": ["ARIA 标签附 Unicode 盲文双通道徽章，默认关闭。", "Optional Unicode braille badges mirroring ARIA labels."],

  // ---- 域15 UI 设计与优化 ----
  "W-176": ["黄金比实验室", "Phi Lab"],
  "W-176d": ["黄金分割/三分线/根矩形参考网格叠加，零交互拦截。", "Phi, thirds and root-rectangle overlays for design review."],
  "W-177": ["白空交响", "Space Symphony"],
  "W-177d": ["相邻元素间距以五线谱呈现，偏离 30% 标红跑调。", "Spacing rhythms as a staff; 30% outliers flagged off-key."],
  "W-178": ["动画成绩单", "Motion Score"],
  "W-178d": ["动效时长/曲线/位移三元一致性体检成绩单。", "A report card on motion duration/curve/distance consistency."],
  "W-179": ["控件考古馆", "Control Museum"],
  "W-179d": ["按钮/滚动条即时换装三代 Windows 风格，10s 归来。", "Controls re-skin through three Windows eras, then return."],
  "W-180": ["网格透视", "Grid X-Ray"],
  "W-180d": ["叠加真实实现网格线框，悬浮显示 span/gap 值。", "X-rays the real CSS grid with span/gap readouts."],
  "W-181": ["字体微唱机", "Type Turntable"],
  "W-181d": ["字重/字距/行高三旋钮实时旋调，满意压盘存预设。", "Spin weight/spacing/leading knobs; press your preset."],
  "W-182": ["图标配重天平", "Icon Balance"],
  "W-182d": ["每图标前景/背景配重与重心偏移体检报告。", "A weight-and-balance report for icon sets."],
  "W-183": ["光标形影一致", "Cursor Consistency"],
  "W-183d": ["五场景光标阴影一致性巡检，跳变处出具体检单。", "Audits cursor shadow consistency across five scenes."],
  "W-184": ["UI 物理热图", "UI Heatmap"],
  "W-184d": ["界面点击密度匿名热图，30 天滚动，隐私开关可停。", "An anonymous click-density heatmap, 30-day rolling."],
  "W-185": ["动画保释官", "Motion Bail"],
  "W-185d": ["无人注视的循环动画降频暂停，回视复庭。", "Unwatched loops get bailed out until seen again."],
  "W-186": ["信息密度湿度计", "Density Meter"],
  "W-186d": ["每屏元素数/留白比/字数三维打分，超密标潮湿。", "Scores each screen's density; soggy pages flagged."],
  "W-187": ["对比度哨兵", "Contrast Sentinel"],
  "W-187d": ["WCAG AA 全文对比度巡检，不达标红框哨兵标记。", "WCAG AA scans with red sentinel boxes on failures."],

  // ---- 域16 工程质量与收官 ----
  "W-188": ["能效标签", "Energy Label"],
  "W-188d": ["空载/启动/动效三轴 A–G 能效评定，阈值公开。", "An A–G energy label across idle, boot and motion."],
  "W-189": ["睡眠孵化器", "Hibernation Nest"],
  "W-189d": ["空闲 30min 应用工作集换出深眠，唤醒热还原。", "Idle 30min apps swap out to sleep; wake restores hot."],
  "W-190": ["崩溃单步重放器", "Crash Replay"],
  "W-190d": ["确定性崩溃逐帧单步重放到崩溃点，仅 dev。", "Single-step replays of deterministic crashes; dev only."],
  "W-191": ["GPU 诊断砚", "GPU Inkstone"],
  "W-191d": ["每帧 GPU 耗时以墨点沉积，越慢墨越浓。", "GPU frame times pool like ink — slower is darker."],
  "W-192": ["多环境军棋推演", "Sandbox Wargame"],
  "W-192d": ["分身 A/B 同负载对照运行产出三方战报。", "Clones A/B run the same load for a three-way report."],
  "W-193": ["内存地平线", "Memory Floor"],
  "W-193d": ["跨版本空载内存最低水位线，逼近红线即警报。", "A cross-version memory floor; nearing the red line alarms."],
  "W-194": ["可复现指纹", "Build Fingerprint"],
  "W-194d": ["同源码两次构建哈希树比对的可复现指纹。", "Hash-tree fingerprints prove build reproducibility."],
  "W-195": ["白纸视角", "Fresh Eyes"],
  "W-195d": ["零设置零历史首跑沙盒，退出即销毁。", "A pristine first-run sandbox, destroyed on exit."],
  "W-196": ["性能气象站", "Perf Weather"],
  "W-196d": ["性能状态气象隐喻播报 + 30 分钟预报。", "Performance as weather, with a 30-minute forecast."],
  "W-197": ["工程星象", "Eng Zodiac"],
  "W-197d": ["12 指标映射 12 星座亮暗的工程命盘。", "Twelve metrics as twelve constellations, bright or dim."],
  "W-198": ["发版礼炮", "Release Cannon"],
  "W-198d": ["发版里程碑墙 + 全屏礼炮，版本号烙入铭牌。", "A milestone wall and cannon salute stamp the release."],
  "W-199": ["性能不朽档案", "Golden Archive"],
  "W-199d": ["各指标历史最佳入档，破纪录时致敬更新。", "Golden records of best-ever numbers, honored when beaten."],
  "W-200": ["测试战绩册", "Test Battle Pass"],
  "W-200d": ["测试里程碑徽章与各域测试功勋墙。", "Badges and honor rolls for the test suite."],

  // ---- 参数名（novaP_*）----
  novaP_diskFactor: ["磁盘繁忙因子权重", "Disk-busy factor weight"],
  novaP_nightSilent: ["深夜自动静默", "Night auto-silence"],
  novaP_staggerMs: ["点亮接力间隔 (ms)", "Ignite stagger (ms)"],
  novaP_windowSec: ["星座可交互窗口 (s)", "Constellation window (s)"],
  novaP_rite: ["告别音制式", "Farewell style"],
  novaP_maxMass: ["重窗面积阈值 (%)", "Heavy-window area (%)"],
  novaP_dampPx: ["阻尼区宽度 (px)", "Damping zone (px)"],
  novaP_maxDepth: ["阴影深度层级", "Shadow depth levels"],
  novaP_idleSec: ["回声触发闲置 (s)", "Echo idle (s)"],
  novaP_idleMin: ["午憩判定 (min)", "Siesta after (min)"],
  novaP_driftPx: ["磁漂幅度 (px)", "Drift range (px)"],
  novaP_peekMs: ["悬停触发 (ms)", "Hover delay (ms)"],
  novaP_arcMs: ["弹道时长 (ms)", "Arc duration (ms)"],
  novaP_ghostN: ["幽灵建议条数", "Ghost suggestions"],
  novaP_chars: ["呼吸提示字数", "Chars per breath"],
  novaP_everyMin: ["眨眼提醒间隔 (min)", "Eye nudge every (min)"],
  novaP_hour: ["触发小时", "Hour"],
  novaP_minute: ["触发分钟", "Minute"],
  novaP_intensity: ["潮汐强度", "Tide intensity"],
  novaP_bolt: ["电流仪式制式", "Bolt style"],
  novaP_freezeMs: ["冻结时长 (ms)", "Freeze duration (ms)"],
  novaP_flock: ["水族馆粒子数", "Aquarium particles"],
  novaP_frame: ["画框制式", "Frame style"],
  novaP_gain: ["雨滴音量 (%)", "Raindrop gain (%)"],
  novaP_zoom: ["布局放大 (%)", "Layout zoom (%)"],

  // ---- 选项值（novaO_*）----
  novaO_strings: ["弦乐收束", "Strings"],
  novaO_pendulum: ["钟摆止息", "Pendulum"],
  novaO_silence: ["静默", "Silence"],
  novaO_thunder: ["雷击", "Thunder"],
  novaO_waterfall: ["瀑布", "Waterfall"],
  novaO_thin: ["典雅细框", "Thin"],
  novaO_gallery: ["画廊厚框", "Gallery"],
  novaO_soft: ["软暗角", "Soft"],
  novaO_film: ["胶片边", "Film"],
  novaO_deckle: ["毛边装裱", "Deckle"],
  novaO_none: ["无", "None"],

  // ---- 新星中枢界面（novaH_*）----
  novaH_title: ["新星中枢", "Nova Hub"],
  novaH_sub: ["NOVA-200 · 200 项能力 · 全部本地运行", "NOVA-200 · 200 capabilities · all local"],
  novaH_search: ["搜索功能（名称/编号）…", "Search features (name / id)…"],
  novaH_on: ["已启用", "Enabled"],
  novaH_off: ["未启用", "Disabled"],
  novaH_open: ["打开", "Open"],
  novaH_reset: ["恢复默认", "Reset"],
  novaH_resetAll: ["全部恢复默认", "Reset all"],
  novaH_close: ["关闭", "Close"],
  novaH_domainAll: ["全部", "All"],
  novaH_statLine: ["已启用 {on}/{total} 项", "{on}/{total} enabled"],
  novaH_noteLocal: ["状态仅保存在本机，零网络。", "State stays on this device. Zero network."],
  novaH_motionNote: ["检测到运动降级：重动效已自动停用。", "Motion reduction detected: heavy effects auto-disabled."],
  novaH_changelog: ["本版能力", "This build"],
};

/** 新星标签翻译（缺键回退 zh → 键名）。 */
export function novaT(key: string, lang: Lang): string {
  const e = NOVA_LABELS[key];
  if (!e) return key;
  return lang === "en" ? e[1] : e[0];
}
