# -*- coding: utf-8 -*-
"""D5 域 B14–B18 数据（M 型机制段收口：F15461–F15560，100 条）。
条目元组：(title, kw, judge, core, ref)"""

B14 = dict(
    bno=14, theme="连接点与持久化 IPersist", mod="comcore::persist",
    blurb="连接点容器、Advise cookie、出事件序、IPersist 流式持久化与版本兼容——M 型机制段第六批",
    deps="B05 QI 全谱；B13 自动化面；comloc 事件面预备",
    gs="连接点/持久化规范（注来源：IConnectionPoint/IPersistStream 章）",
    entries=[
        ("IConnectionPointContainer 面谱", "CP容器",
         "容器面成文（EnumConnectionPoints/FindConnectionPoint 双法 10/10 次），伪容器注入（无出事件谎报）检出 10/10 次",
         "连接点容器面谱：可连接对象的出事件能力声明与枚举——出事件契约的入口。",
         "与 IConnectionPointContainer 语义对照"),
        ("FindConnectionPoint 枚举与未命中", "CP查找",
         "查找成文（命中返回/未命中 CONNECT_E_NOCONNECTION 10/10 次），假命中注入检出 10/10 次",
         "FindConnectionPoint 语义：命中即出接口点、未命中如实报——不假装支持出事件。",
         "与 FindConnectionPoint 错误语义对照"),
        ("Advise/Unadvise cookie 语义", "cookie账",
         "cookie 账成文（cookie 唯一分配/注销配对 10/10 次），重注销注入（同 cookie 二次注销）检出 10/10 次",
         "Advise 返回 cookie、Unadvise 凭 cookie 注销——cookie 账是 sink 生命周期的凭证链。",
         "与 Advise/Unadvise cookie 语义对照"),
        ("出事件调用序与重入防护", "出事件序",
         "出事件序成文（sink 调用序冻结+重入防护 10/10 次），重入注入（sink 内再 Advise 死锁形态）检出 10/10 次",
         "出事件按注册序广播且防重入：sink 回调中再动连接表是死锁/重入根源——防护线钉死。",
         "与出事件调用（sink notify）惯例对照"),
        ("IPersist::GetClassID 面", "GetClassID",
         "GetClassID 成文（CLSID 回报稳定 10/10 次），漂移注入（两次回报不同）检出 10/10 次",
         "持久化第一法：对象自报 CLSID——容器凭它找到同类工厂重建，ID 漂移即持久化破。",
         "与 IPersist::GetClassID 语义对照"),
        ("IPersistStream Load/Save 链", "流持久化",
         "Load/Save 链成文（Save→Load 往返保真 30 档 10/10 次），短流注入（截断流 Load）如实拒断言",
         "流式持久化：Save 序列化/Load 还原往返保真——坏流（短流/坏版本）如实拒不半装。",
         "与 IPersistStream::Load/Save 语义对照"),
        ("IPersistStorage 复合文档预备", "存储持久化",
         "存储预备成文（IStorage 槽位接口冻结+fake 收口 10/10 次），接口漂移注入检出 10/10 次",
         "IPersistStorage 复合文档持久化预备：B15 存储面未落前接口冻结+fake——Schema 先行不等待。",
         "与 IPersistStorage 语义对照"),
        ("持久化版本兼容账（版本+污位）", "版本兼容",
         "兼容账成文（版本头校验+漂移如实报 10/10 次），版本穿透注入（旧版数据静默误读）检出 10/10 次",
         "持久化版本账：流头带版本号，旧版数据按兼容表解读或如实拒——静默误读是数据破坏根源。",
         "与版本化流（versioned stream）惯例对照"),
        ("sink 引用对账审计", "sink对账",
         "对账成文（Advise 计数与 sink 持有恒等 10/10 次），泄漏注入（Unadvise 后引用残留）检出 10/10 次",
         "连接点泄漏审计：Advise 持有的 sink 引用逐对记账——Unadvise 后残留引用即泄漏环源。",
         "与连接点泄漏（连接未断）惯例对照"),
        ("持久化注入矩阵", "注入矩阵",
         "注入矩阵 10 格全检（伪容器/假命中/重注销/重入/ID 漂移/短流/接口漂移/版本穿透/sink 泄漏/污位丢失 10/10 次检出）",
         "连接点×持久化负判据封口条：10 格坏形态注入全检——出事件与持久化双面无死角。",
         "与两违约面集合对照"),
        ("多 sink 广播并发序", "并发广播",
         "并发序成文（多 sink 并发广播序冻结+单 sink 异常隔离 10/10 次），扩散注入（单 sink 崩拖垮广播）检出 10/10 次",
         "多 sink 广播并发序：注册序广播、单 sink 异常隔离不扩散——沙箱隔离纪律在出事件的落点。",
         "与多连接点广播（isolation）惯例对照"),
        ("持久化 comloc/资源面回归", "comloc回归",
         "回归全绿（事件面/流面 comloc 承诺 10/10 次），漂移注入必红",
         "连接点与持久化面建成后的基线回归：comloc 事件/流承诺零漂移。",
         "与 comloc.rs 事件承诺面对照"),
    ],
)

B15 = dict(
    bno=15, theme="结构化存储与统一传输", mod="comcore::storage",
    blurb="IStorage/IStream 基座、枚举、事务预备、IDataObject 格式协商与 TYMED 分族——M 型机制段第七批",
    deps="B14 IPersistStorage 冻结接口；B12 数据面；comloc Clipboard 面",
    gs="结构化存储规范（注来源：IStorage/IStream/复合文件章）+OLE 统一数据传输（FORMATETC/STGMEDIUM）",
    entries=[
        ("IStorage/IStream 复合文件基座", "存储基座",
         "基座成文（存储/流双元素创建/打开/删除 10/10 次），悬空元素注入（删除后打开）如实拒断言",
         "结构化存储基座：存储（目录）与流（数据）双元素语义——复合文件的逻辑层。",
         "与 IStorage/IStream（structured storage）对照"),
        ("复合文件布局预备（FAT/目录树）", "布局预备",
         "布局预备成文（扇区/FAT/目录树映射账 10/10 次），布局漂移注入检出 10/10 次",
         "复合文件物理层预备：扇区分配表与目录树映射账——逻辑元素到字节布局的桥（正式实装随 B 系后批）。",
         "与 CFB（Compound File Binary）布局对照"),
        ("存储元素枚举（IEnumSTATSTG）", "枚举器",
         "枚举成文（Next/Skip/Reset/Clone 四法+快照语义 10/10 次），并发变注入（枚举中增删）检出 10/10 次",
         "IEnumSTATSTG 枚举器：存储子树快照式枚举——枚举中的并发变更语义钉版。",
         "与 IEnumSTATSTG 快照语义对照"),
        ("事务模式预备（commit/rollback）", "事务预备",
         "事务预备成文（STGM_TRANSACTED 接口冻结+fake 收口 10/10 次），半提交注入检出 10/10 次",
         "存储事务模式预备：提交/回滚接口冻结+fake——断电一致性（域宪法关联）随实装批深化。",
         "与 transacted storage（commit/rollback）对照"),
        ("IDataObject 面谱（FORMATETC/STGMEDIUM）", "IDataObject",
         "面谱成文（GetData/SetData/EnumFormatEtc 三法 10/10 次），野格式注入（未登记 CF）检出 10/10 次",
         "统一数据传输门面：FORMATETC 描述格式、STGMEDIUM 载体——IDataObject 是剪贴板与拖放共用面。",
         "与 IDataObject/FORMATETC/STGMEDIUM 语义对照"),
        ("剪贴板格式协商", "格式协商",
         "协商成文（多格式优先序协商 10/10 次），降级注入（首选格式缺位时静默降级）如实报断言",
         "格式协商：数据以多格式供给、消费方按优先序协商——降级必须显性化不静默。",
         "与 OLE 剪贴板格式协商对照"),
        ("TYMED 分族传输（HGLOBAL/IStream/FILE 等）", "TYMED分族",
         "分族成文（TYMED 四族载体存取 10/10 次），错族注入（载体与 medium 不符）检出 10/10 次",
         "TYMED 分族：HGLOBAL/IStream/FILE/GDI 四族载体各有存取规则——载体与声明不符即红。",
         "与 TYMED 枚举语义对照"),
        ("存储损坏检测账", "损坏检测",
         "检测账成文（签名/校验和/结构三查 10/10 次），坏档注入（三查任一破）如实报断言",
         "存储损坏检测：签名、校验和、结构三查——坏档如实报不静默修复（数据安全红线面）。",
         "与复合文件校验（CDFB 签名 0xD0CF11E0）对照"),
        ("传输注入矩阵", "注入矩阵",
         "注入矩阵 10 格全检（悬空元素/布局漂移/并发变/半提交/野格式/静默降级/错族/坏档/短流/枚举破 10/10 次检出）",
         "存储传输负判据封口条：10 格坏形态注入全检——数据进出系统的大门无死角。",
         "与传输违约形态集合对照"),
        ("存储×D3 激活信息联动预备", "D3联动",
         "联动预备成文（文件→注册表激活信息通道冻结 10/10 次），漂移注入检出 10/10 次",
         "存储与 D3 联动预备：文件型激活（moniker 前奏）经注册表通道——D3 键面已收口可引。",
         "与文件激活（文档→应用）注册面惯例对照"),
        ("大块传输零拷贝路径", "零拷贝",
         "零拷贝成文（IStream 直传路径断言 10/10 次），多余拷贝注入检出 10/10 次",
         "大块数据经 IStream 直传零中间拷贝——传输性能账，丰盛不以卡顿为代价。",
         "与大块传输（streaming）惯例对照"),
        ("OLE 剪贴板 Windows 对照观测", "观测对照",
         "观测全绿（真实 Windows 剪贴板形态 12 格对照 ≥9 一致），差异格分级账",
         "Windows 对照观测：真实系统剪贴板/存储行为 12 格逐格对照——差异分级回写。",
         "与真实 Windows OLE 剪贴板观测（真机对照）比对"),
    ],
)

B16 = dict(
    bno=16, theme="Moniker 绑定与命名激活", mod="comcore::moniker",
    blurb="IMoniker 面谱、文件/组合 moniker、ROT 预备、绑定上下文与解析链——M 型机制段第八批",
    deps="B11 激活链；B15 存储×D3 联动；D3 注册表键面",
    gs="moniker 规范（注来源：IMoniker/IBindCtx/ROT 章）+D3 已收口段",
    entries=[
        ("IMoniker 面谱与绑定链", "moniker面谱",
         "面谱成文（BindToObject/BindToStorage 双核 10/10 次），假绑定注入（未解析即返回对象）检出 10/10 次",
         "IMoniker 是「命名的激活」：BindToObject 解析名字到对象、BindToStorage 到数据——绑定链是 moniker 的核。",
         "与 IMoniker::BindToObject 语义对照"),
        ("文件 moniker（FileMoniker）", "FileMoniker",
         "文件 moniker 成文（路径解析→B11 激活链 10/10 次），坏路径注入如实拒断言",
         "FileMoniker：文件路径到文档对象激活——经 B15 存储面与 B11 激活链贯通。",
         "与 File Moniker 语义对照"),
        ("组合 moniker（Composite 前缀/枚举）", "组合moniker",
         "组合成文（前缀组合/枚举/化简 10/10 次），环组合注入（自组合）检出 10/10 次",
         "Composite moniker：名字的拼接与化简——组合语义支持「容器里的对象」式路径激活。",
         "与 Generic Composite moniker 语义对照"),
        ("ROT 运行对象表预备", "ROT预备",
         "ROT 预备成文（Register/Revoke/GetObject 接口冻结+fake 10/10 次），野注册注入检出 10/10 次",
         "运行对象表（ROT）预备：已运行对象的登记/查询——「先找运行实例再新起」的账（随 D2/D4 联签实装）。",
         "与 Running Object Table 语义对照"),
        ("绑定上下文（IBindCtx）参数面", "BindCtx",
         "上下文成文（参数账/对象账双账 10/10 次），串账注入（上下文间泄漏）检出 10/10 次",
         "IBindCtx 绑定上下文：绑定参数与中间对象双账——上下文是绑定的环境句柄，账目隔离。",
         "与 IBindCtx（BIND_OPTS/对象账）对照"),
        ("moniker 解析链（Reduce/ComposeWith）", "解析链",
         "解析链成文（Reduce/ComposeWith/Inverse 三核 10/10 次），断链注入检出 10/10 次",
         "moniker 解析链：Reduce 化简、ComposeWith 组合、Inverse 反转三核——名字代数的运算律。",
         "与 IMoniker::Reduce/ComposeWith 语义对照"),
        ("绑定失败三要素呈现", "失败三要素",
         "三要素成文（绑定失败富错误三要素 10/10 次），裸码注入检出 10/10 次",
         "绑定失败富错误：人话（哪个名字）/原因（哪段断）/下一步（路径修正）——B07 三要素红线在 moniker 的落点。",
         "与 MK_E_* 错误族语义对照"),
        ("moniker×D3 名称解析联动", "D3联动",
         "联动成文（名字→D3 键面解析通道 10/10 次），漂移注入检出 10/10 次",
         "moniker 名字解析与 D3 联动：类名/路径到激活信息的键面通道——D3 已收口段直接消费。",
         "与名字解析注册面（HKCR 类别名）惯例对照"),
        ("moniker 注入矩阵", "注入矩阵",
         "注入矩阵 10 格全检（假绑定/坏路径/自组合/野注册/串账/断链/裸码/漂移/环解析/越权绑定 10/10 次检出）",
         "moniker 负判据封口条：10 格坏形态注入全检——命名激活面无死角。",
         "与 moniker 违约形态集合对照"),
        ("moniker 生命周期账", "生命周期账",
         "生命周期账成文（moniker 创建/绑定/释放恒等 10/10 次），残账注入检出 10/10 次",
         "moniker 也过账本：创建/绑定/释放三态记账——与零泄漏账主轴（域宪法②）同构。",
         "与名字对象生命周期惯例对照"),
        ("绑定缓存性能账", "绑定缓存",
         "缓存账成文（绑定结果缓存命中/失效 10/10 次），陈旧注入（缓存指向已失效对象）检出 10/10 次",
         "绑定缓存：重复绑定同名字走缓存——对象失效即缓存失效，陈旧必检。",
         "与绑定缓存（moniker caching）惯例对照"),
        ("moniker 面 Windows 对照观测", "观测对照",
         "观测全绿（真实 moniker 行为 12 格对照 ≥9 一致），差异格分级账",
         "Windows 对照观测：真实系统 moniker 绑定行为 12 格对照——差异分级回写。",
         "与真实 Windows moniker 行为（真机对照）比对"),
    ],
)

B17 = dict(
    bno=17, theme="OLE 拖放与剪贴板传输", mod="comcore::oledrag",
    blurb="IDropSource/IDropTarget 全谱、DoDragDrop 循环、DROPEFFECT 协商与 comloc 接管回归——M 型机制段第九批",
    deps="B15 IDataObject 面；D4 消息泵（Schema 先行 R-D5-001）；comloc DropSource 本地对象（F019 承诺面）",
    gs="OLE 拖放规范（注来源：DoDragDrop/DROPEFFECT 章）+comloc.rs DropSource 承诺差异表",
    entries=[
        ("IDropSource/IDropTarget 全谱", "拖放全谱",
         "全谱成文（两端五法签名语义 10/10 次），缺法注入检出 10/10 次",
         "OLE 拖放两端：源（IDropSource）供数据、的（IDropTarget）收数据——五法全谱是拖放合同。",
         "与 IDropSource/IDropTarget 接口规范对照"),
        ("DoDragDrop 循环语义（D4 冻结联动）", "拖放循环",
         "循环成文（捕获→反馈→判定→落点四段+fake 泵 10/10 次），循环断链注入检出 10/10 次",
         "DoDragDrop 主循环：鼠标捕获、效果反馈、目标判定、落点交付四段——D4 泵 Schema 先行 fake 收口。",
         "与 DoDragDrop 循环（mouse capture）对照"),
        ("DROPEFFECT 协商（移动/复制/链接/滚动）", "效果协商",
         "协商成文（四效果位与源允许集交运算 10/10 次），越权注入（源未允许的效应落地）检出 10/10 次",
         "DROPEFFECT 协商：目标请求效果与源允许效果求交——越权效果（源未允许的移动）必拒。",
         "与 DROPEFFECT 位语义对照"),
        ("GiveFeedback/QueryContinue 反馈链", "反馈链",
         "反馈链成文（光标反馈/继续判定双回调序 10/10 次），逃逸注入（Esc 中断漏路）检出 10/10 次",
         "反馈链：GiveFeedback 光标反馈、QueryContinue 继续/取消判定——Esc 取消是承诺路径。",
         "与 GiveFeedback/QueryContinue 语义对照"),
        ("拖放数据经 IDataObject 通道", "数据通道",
         "通道成文（拖放数据全程经 IDataObject 10/10 次），旁路注入（私有通道绕行）检出 10/10 次",
         "拖放数据只走 IDataObject 统一通道——与剪贴板同构（B15），旁路通道即违例。",
         "与拖放经 IDataObject 传输语义对照"),
        ("剪贴板 Open/Set/Close 序律", "剪贴板序",
         "序律成文（Open→Set→Close 配对+超时自动闭 10/10 次），裸 Set 注入（未 Open 直写）检出 10/10 次",
         "剪贴板序律：Open/Set/Close 配对、异常路径自动闭——占用泄漏即系统级卡剪贴板根源。",
         "与 OpenClipboard/SetClipboardData 语义对照"),
        ("延迟渲染（NULL medium 语义）", "延迟渲染",
         "延迟渲染成文（挂起格式按需合成 10/10 次），伪延迟注入（合成失败冒成功）检出 10/10 次",
         "延迟渲染：大数据先声明格式、取用时按需合成——合成失败必须显性化不冒成功。",
         "与 delayed rendering（NULL STGMEDIUM）语义对照"),
        ("comloc DropSource 接管回归", "接管回归",
         "接管回归全绿（DropSource/Clipboard/AppActivation 三本地对象行为 10/10 次），漂移注入必红",
         "comloc 四族本地对象中拖放相关三族接管回归：行为逐锚对表零漂移——升级接管体例的回归锚。",
         "与 comloc.rs DropSource 承诺差异表对照"),
        ("拖放注入矩阵", "注入矩阵",
         "注入矩阵 10 格全检（缺法/断链/越权/逃逸漏/旁路/裸 Set/伪延迟/漂移/半拖销毁/双拖并发 10/10 次检出）",
         "拖放负判据封口条：10 格坏形态注入全检——拖放是用户最直接的交互面，无死角。",
         "与拖放违约形态集合对照"),
        ("拖放审计埋点", "拖放审计",
         "埋点成文（拖放全链埋点：源发起/目标进出/落点/取消 10/10 次链完整），断链注入检出 10/10 次",
         "拖放全链审计埋点：交互细节级留痕（十三·体验日志红线）——拖放挫败信号可回放。",
         "与交互日志（体验埋点）惯例对照"),
        ("拖动帧性能账", "拖动性能",
         "性能账成文（拖动帧内主线程无阻塞断言 10/10 次），卡顿注入（拖动中重活）检出 10/10 次",
         "拖动帧性能账：拖动路径零重活、帧率稳定——丰盛不以卡顿为代价的交互落点。",
         "与拖放帧率（60fps 惯例）对照"),
        ("拖放面 Windows 对照观测", "观测对照",
         "观测全绿（真实拖放行为 12 格对照 ≥9 一致），差异格分级账",
         "Windows 对照观测：真实系统拖放行为（MFC 样本交互）12 格对照——真机判据随闸门补测（R-D5-002）。",
         "与真实 Windows 拖放行为（真机对照）比对"),
    ],
)

B18 = dict(
    bno=18, theme="ActiveX 容器契约与波段总聚合", mod="comcore::axhost",
    blurb="IOleObject 契约、站点链、就地激活预备、comloc 总回归与 B04–B18 波段守恒闭合——M 型机制段收官批",
    deps="B04–B17 全部已收口批；comloc 四族本地对象（F019 承诺面）；D2 进程链（LocalServer 冻结）",
    gs="ActiveX 容器契约规范（注来源：IOleObject/IOleClientSite 章）+《AI分工完成图》AI-13 任务书",
    entries=[
        ("IOleObject 契约面谱", "IOleObject",
         "面谱成文（二十法核心八法语义断言 10/10 次），缺法注入检出 10/10 次",
         "IOleObject 是控件与容器的总合同：站点/客户区/关闭/显示八法核心面——契约面谱钉版。",
         "与 IOleObject 核心方法语义对照"),
        ("IOleClientSite 站点链", "站点链",
         "站点链成文（容器→站点→控件单向链 10/10 次），环引用注入（站点持控件强引用）检出 10/10 次",
         "站点链：容器经 IOleClientSite 供环境、控件只持站点弱向——环引用即泄漏环，方向律钉死。",
         "与 OLE 站点（site）持有方向惯例对照"),
        ("就地激活预备（in-place）", "就地激活",
         "就地预备成文（IOleInPlaceObject 接口冻结+fake 10/10 次），接口漂移注入检出 10/10 次",
         "就地激活预备：控件嵌入容器客户区的接口族冻结+fake 收口——UI 激活随 D4/UI 批联签实装。",
         "与 in-place activation 接口族对照"),
        ("属性页联动（B14 持久化复用）", "属性页联动",
         "联动成文（属性经 B12 数据面+B14 持久化读写 10/10 次），旁路注入检出 10/10 次",
         "控件属性页联动：属性读写复用 VARIANT 数据面与持久化链——属性即持久化状态的可视面。",
         "与属性页（IPropertyPage）惯例对照"),
        ("控件事件经连接点回传（B14 复用）", "事件回传",
         "回传成文（控件出事件经 B14 连接点到容器 10/10 次），断链注入检出 10/10 次",
         "控件事件回传：出事件经连接点机制到达容器 sink——B14 出事件序与重入防护直接复用。",
         "与控件事件（event sink）语义对照"),
        ("脚本化控件安全拒止预备", "安全拒止",
         "拒止预备成文（脚本安全分类账+拒止清单 10/10 次），越权实例化注入检出 10/10 次",
         "脚本化控件安全面：Categories of safe-for-scripting 分类账、未分类控件脚本路径拒止——安全面前置。",
         "与 safe-for-scripting/initialization 类别语义对照"),
        ("comloc 四族本地对象接管总回归", "总回归",
         "总回归全绿（ShellLink/DropSource/Clipboard/AppActivation 四族逐族 10/10 次），漂移注入必红",
         "接管基线总回归：comloc 四族本地对象（F019 承诺面）全域行为逐族对表——升级接管体例的总锚。",
         "与 comloc.rs 四族承诺差异表逐族对照"),
        ("波段总索引（B04–B18 十五批）", "波段总索引",
         "总索引成文（15 批 300 条四列索引勾稽 300/300 零缺漏），索引漂移注入检出",
         "B04–B18 波段总索引：批号/主题/条数/边界四列——波段产出的总账入口。",
         "与 D3 B30 总聚合体例（F14181 同构）对照"),
        ("波段守恒闭合（300 项三重守恒）", "守恒闭合",
         "守恒闭合（条数 300+行数 90,000+判据 300 三重断言），十五册指纹归并链零缺环",
         "波段守恒闭合：B04–B18 十五批 300 条条数/行数/判据三重守恒——域累计精确达 108,000/240,000。",
         "与波次守恒闭合体例（F14196 同构）对照"),
        ("体验完整性对表（14 章映射）", "体验对表",
         "对表成文（14 章×波段交互点映射、覆盖 14/14 断言），缺口章检出必红",
         "体验完整性 14 章与本波段交互面映射：拖放/剪贴板/绑定/错误三要素逐章对表——体验红线收口。",
         "与体验完整性十四章制度（Variable 明令）对照"),
        ("红线对表与防重总声明", "红线防重",
         "对表成文（硬件红线三族零违反+防重嫌疑清单=空 10/10 次），嫌疑项检出必红",
         "波段红线对表：无引导/硬件数据安全红线条目声明复核+300 条全域防重聚类嫌疑清空。",
         "与红线制度条款与防重五范围制度对照"),
        ("波段收官章（总锚+handoff 滚动）", "收官章",
         "收官章成文（波段总锚归并+handoff 滚动声明+B19–B40 待领口径），20 维自查挂钩表在册",
         "波段收官章：B04–B18 总锚归并、handoff 滚动声明（300 项新功能明令达成 300/300）、后续批滚动口径。",
         "与波次收官章体例（F14200 同构）对照"),
    ],
)
