#
#
# interface_version: varix-bli-1
# hash: f1d824be
timeout: 5
serial: yes
default_entry: 0

/kernel/varix
    protocol: limine
    kernel_path: boot():/kernel/varix
    kernel_cmdline: desktop=1 boot_timeout=0 panic_halt=1
    comment: VARIX kernel (STAR I)

/Windows 11 (USB)
    protocol: efi
    path: guid(636786cb-e967-49f6-b0df-7608909d1f11):/EFI/Microsoft/Boot/bootmgfw.efi
    comment: handoff target (WINESP 636786cb-e967-49f6-b0df-7608909d1f11)