/**
 * 车道 W 本地词典（计划口径：各车道自建 lane 词典，不改 i18n/dictionaries.ts）。
 */

export const WP_LABELS = {
  zh: {
    title: "壁纸工坊 2.0",
    tabVideo: "视频",
    tabShader: "着色器",
    tabGenerative: "生成式",
    tabWeb: "网页",
    tabPack: "壁纸包 (.vwp)",
    pickFile: "选择文件…",
    apply: "应用到桌面",
    applied: "已向主控发送应用请求（ai04:wallpaper-apply，集成阶段接入）",
    close: "关闭",
    preview: "实时预览",
    videoPreviewOnly: "浏览器模式：仅本地预览，无法取得文件路径，应用按钮不可用",
    perfGate: "性能联动",
    gateTyping: "打字降级",
    gateFullscreen: "全屏降帧",
    gateBattery: "电池暂停",
    gateNone: "正常",
    shaderPickHint: "支持本地 .frag / .glsl（WE 兼容，编译失败自动降级静态帧）",
    shaderUniforms: "参数滑杆（来自源码注释声明）",
    shaderFailed: "着色器编译失败，已降级为静态帧",
    shaderApplyNeedsPath: "应用着色器需要本地文件路径（Tauri 文件对话框选择）",
    genPresets: "生成式预设",
    genFlow: "流动",
    genParallax: "视差",
    genNote: "应用后映射为「引力场」星空：流动→dynamicStrength，视差→parallaxStrength",
    webPath: "当前网页壁纸",
    webNetline: "禁网边界：网页壁纸仅允许本地 html；远程地址一律拒绝",
    webRejected: "已拒绝：仅允许本地 html 文件",
    packImport: "导入 .vwp",
    packExport: "导出当前预设为 .vwp",
    packOk: "校验通过",
    packErr: "校验失败",
    packErrFormat: "不是 .vwp（format/version 不符）",
    packErrKind: "kind 不合法（仅 shader/web/generative）",
    packErrManifest: "manifest 缺失或无名",
    packErrUniforms: "uniforms 含非数值",
    packErrResourceUrl: "红线：resources 含远程 URL（http/file），已拒绝加载",
    packErrResourceType: "resources 含未允许的 data 类型",
    packErrResourceSize: "resources 单项超过 2MB",
    packImportPreview: "导入包预览",
    packImportNoApply: "导入包仅预览：应用桌面壁纸需本地文件路径（安全边界）",
    packExportShaderNeed: "导出 shader 包需先在「着色器」页加载源码",
    packExportWebTry: "正在通过本地资源协议读取 html…",
    packExportWebFail: "读取本地 html 失败（非 Tauri 环境）",
    sceneEntry: "实况场景设置…",
    centerEntry: "壁纸中心…",
    videoNoFile: "未选择视频",
    shaderNoFile: "未加载着色器源码",
  },
  en: {
    title: "Wallpaper Studio 2.0",
    tabVideo: "Video",
    tabShader: "Shader",
    tabGenerative: "Generative",
    tabWeb: "Web",
    tabPack: "Pack (.vwp)",
    pickFile: "Pick file…",
    apply: "Apply to desktop",
    applied: "Apply request sent to shell (ai04:wallpaper-apply, wired at integration)",
    close: "Close",
    preview: "Live preview",
    videoPreviewOnly: "Browser mode: preview only (no file path), apply disabled",
    perfGate: "Perf gate",
    gateTyping: "Typing degrade",
    gateFullscreen: "Fullscreen 10fps",
    gateBattery: "Battery pause",
    gateNone: "Normal",
    shaderPickHint: "Local .frag / .glsl (WE-compatible; compile failure degrades to a static frame)",
    shaderUniforms: "Uniform sliders (declared in source comments)",
    shaderFailed: "Shader compile failed; degraded to static frame",
    shaderApplyNeedsPath: "Applying requires a real file path (Tauri file dialog)",
    genPresets: "Generative presets",
    genFlow: "Flow",
    genParallax: "Parallax",
    genNote: "Applies as Gravity starfield: flow→dynamicStrength, parallax→parallaxStrength",
    webPath: "Current web wallpaper",
    webNetline: "Offline-only: local html files only; remote URLs are rejected",
    webRejected: "Rejected: local html files only",
    packImport: "Import .vwp",
    packExport: "Export current preset as .vwp",
    packOk: "Valid",
    packErr: "Invalid",
    packErrFormat: "Not a .vwp (format/version mismatch)",
    packErrKind: "Bad kind (shader/web/generative only)",
    packErrManifest: "Missing manifest or name",
    packErrUniforms: "Non-numeric uniforms",
    packErrResourceUrl: "Red line: remote URL in resources (http/file) rejected",
    packErrResourceType: "Disallowed data type in resources",
    packErrResourceSize: "Resource exceeds 2MB",
    packImportPreview: "Imported pack preview",
    packImportNoApply: "Imported packs are preview-only: applying needs a local path (security)",
    packExportShaderNeed: "Load shader source in the Shader tab first",
    packExportWebTry: "Reading local html via asset protocol…",
    packExportWebFail: "Failed to read local html (non-Tauri environment)",
    sceneEntry: "Living scene settings…",
    centerEntry: "Wallpaper Center…",
    videoNoFile: "No video selected",
    shaderNoFile: "No shader source loaded",
  },
} as const;

export type WpLabelKey = keyof (typeof WP_LABELS)["zh"];

/** 简单语言选择：navigator.language 以 zh 开头用中文，否则英文（本地判定，零依赖）。 */
export function wpT(lang?: string): (k: WpLabelKey) => string {
  const l = lang ?? (typeof navigator !== "undefined" ? navigator.language : "zh");
  const dict = WP_LABELS[l && l.toLowerCase().startsWith("zh") ? "zh" : "en"];
  return (k) => dict[k] ?? k;
}