import type { Lang } from "../../i18n/dictionaries";

/**
 * Z-24 字符与 Emoji 面板 —— 纯数据与纯函数模块（AI-08）。
 * 红线：
 * - 只做字符复制，不解析剪贴板、不监听输入法
 * - 数据为静态精选集（约 400+），不做联网扩充 / 用户自定义表情管理
 * - recent 仅存 emoji 本体字符串（不存使用时间等隐私轨迹），上限 24
 */

export interface EmojiItem {
  /** emoji 本体（旗帜为双 regional indicator 字符） */
  ch: string;
  /** 中文描述（搜索子串用，简体） */
  zh: string;
  /** 英文描述（搜索用，比较时大小写不敏感） */
  en: string;
}

export interface EmojiCategory {
  id: string;
  zh: string;
  en: string;
  /** 侧栏分类图标 */
  icon: string;
  items: EmojiItem[];
}

// ---------- 九大分类数据 ----------

const SMILEYS: EmojiItem[] = [
  { ch: "😀", zh: "咧嘴笑", en: "grinning face" },
  { ch: "😃", zh: "笑脸大眼", en: "smiley face big eyes" },
  { ch: "😄", zh: "开怀笑脸", en: "big smile happy face" },
  { ch: "😅", zh: "汗颜笑", en: "sweat smile" },
  { ch: "😆", zh: "眯眼大笑", en: "laughing squint face" },
  { ch: "😁", zh: "露齿咧嘴笑", en: "beaming face teeth" },
  { ch: "😉", zh: "眨眼", en: "winking face" },
  { ch: "😊", zh: "微笑脸红", en: "blushing smile" },
  { ch: "😋", zh: "好吃", en: "yummy face" },
  { ch: "😍", zh: "爱慕", en: "heart eyes love" },
  { ch: "😘", zh: "飞吻", en: "kiss blowing heart" },
  { ch: "😗", zh: "亲吻", en: "kissing face" },
  { ch: "😙", zh: "含笑亲吻", en: "kissing smiling eyes" },
  { ch: "😚", zh: "闭眼亲吻", en: "kissing closed eyes" },
  { ch: "😜", zh: "吐舌眨眼", en: "wink tongue zany" },
  { ch: "😝", zh: "眯眼吐舌", en: "squint tongue" },
  { ch: "🤪", zh: "滑稽疯", en: "zany crazy face" },
  { ch: "🤨", zh: "挑眉", en: "raised eyebrow" },
  { ch: "🧐", zh: "单片眼镜", en: "monocle face" },
  { ch: "🤓", zh: "书呆子", en: "nerd face" },
  { ch: "😎", zh: "墨镜", en: "sunglasses cool" },
  { ch: "🥳", zh: "庆祝派对", en: "party celebrate" },
  { ch: "😏", zh: "坏笑", en: "smirk face" },
  { ch: "😒", zh: "不高兴", en: "unamused face" },
  { ch: "😞", zh: "失望", en: "disappointed sad" },
  { ch: "😔", zh: "忧郁", en: "pensive face" },
  { ch: "😟", zh: "担忧", en: "worried face" },
  { ch: "😕", zh: "困惑", en: "confused face" },
  { ch: "🙁", zh: "皱眉", en: "frown slightly" },
  { ch: "☹️", zh: "不快", en: "frowning face" },
  { ch: "😣", zh: " persevere 坚持", en: "persevere face" },
  { ch: "😖", zh: "困窘", en: "confounded face" },
  { ch: "😫", zh: "疲惫", en: "tired face" },
  { ch: "😩", zh: "乏力", en: "weary face" },
  { ch: "🥺", zh: "恳求", en: "pleading puppy eyes" },
  { ch: "😢", zh: "哭", en: "crying tear" },
  { ch: "😭", zh: "嚎啕大哭", en: "loudly crying sob" },
  { ch: "😤", zh: "生气", en: "triumph huff face" },
  { ch: "😠", zh: "愤怒", en: "angry mad face" },
  { ch: "😡", zh: "暴怒", en: "rage pouting red" },
  { ch: "🤬", zh: "骂人", en: "cursing swearing" },
  { ch: "🤯", zh: "脑子炸了", en: "exploding head mind blown" },
  { ch: "😳", zh: "脸红", en: "flushed embarrassed" },
  { ch: "🥵", zh: "热", en: "hot overheat" },
  { ch: "🥶", zh: "冷", en: "cold freezing" },
  { ch: "😱", zh: "尖叫", en: "scream fear" },
  { ch: "😨", zh: "害怕", en: "fearful face" },
  { ch: "😰", zh: "焦虑", en: "anxious sweat" },
  { ch: "😥", zh: "失望释然", en: "sad relieved" },
  { ch: "😓", zh: "冷汗", en: "downcast sweat" },
  { ch: "🤗", zh: "拥抱", en: "hug smiling" },
  { ch: "🤔", zh: "思考", en: "thinking face" },
  { ch: "🤭", zh: "掩嘴笑", en: "hand over mouth giggle" },
  { ch: "🤫", zh: "嘘", en: "shush quiet" },
  { ch: "🤥", zh: "撒谎", en: "lying face pinocchio" },
  { ch: "😶", zh: "沉默", en: "no mouth silent" },
  { ch: "😐", zh: "无表情", en: "neutral face" },
  { ch: "😑", zh: "面无表情", en: "expressionless" },
  { ch: "😬", zh: "呲牙", en: "grimace teeth" },
  { ch: "🙄", zh: "翻白眼", en: "rolling eyes" },
  { ch: "😯", zh: "愕然", en: "hushed face" },
  { ch: "😦", zh: "皱眉张嘴", en: "frowning open mouth" },
  { ch: "😧", zh: "苦恼", en: "anguished" },
  { ch: "😮", zh: "惊讶", en: "open mouth wow" },
  { ch: "😲", zh: "震惊", en: "astonished flushed" },
  { ch: "🥱", zh: "打哈欠", en: "yawning sleepy" },
  { ch: "😴", zh: "睡觉", en: "sleeping zzz" },
  { ch: "💩", zh: "便便", en: "poop pile" },
  { ch: "🤡", zh: "小丑", en: "clown face" },
  { ch: "👻", zh: "鬼", en: "ghost halloween" },
  { ch: "💀", zh: "骷髅", en: "skull death" },
  { ch: "👽", zh: "外星人", en: "alien ufo" },
  { ch: "🤖", zh: "机器人", en: "robot bot" },
  { ch: "🎃", zh: "南瓜灯", en: "jack-o-lantern" },
];

const GESTURES: EmojiItem[] = [
  { ch: "👋", zh: "挥手", en: "waving hand hello" },
  { ch: "🤚", zh: "手背", en: "raised back hand" },
  { ch: "🖐️", zh: "张开手掌", en: "hand fingers splayed" },
  { ch: "✋", zh: "举手", en: "raised hand stop" },
  { ch: "🖖", zh: "瓦肯礼", en: "vulcan salute spock" },
  { ch: "👌", zh: "OK 手势", en: "ok hand sign" },
  { ch: "🤌", zh: "捏手指", en: "pinched fingers" },
  { ch: "🤏", zh: "捏一点", en: "pinching hand little" },
  { ch: "✌️", zh: "胜利手势", en: "victory peace sign" },
  { ch: "🤞", zh: "交叉手指", en: "crossed fingers lucky" },
  { ch: "🤟", zh: "爱你手势", en: "love you sign" },
  { ch: "🤘", zh: "摇滚手势", en: "horns rock on" },
  { ch: "🤙", zh: "打电话手势", en: "call me hand shaka" },
  { ch: "👈", zh: "向左指", en: "point left" },
  { ch: "👉", zh: "向右指", en: "point right" },
  { ch: "👆", zh: "向上指", en: "point up" },
  { ch: "👇", zh: "向下指", en: "point down" },
  { ch: "☝️", zh: "食指向上", en: "index pointing up" },
  { ch: "👍", zh: "点赞", en: "thumbs up like" },
  { ch: "👎", zh: "点踩", en: "thumbs down dislike" },
  { ch: "✊", zh: "握拳", en: "raised fist" },
  { ch: "👊", zh: "出拳", en: "punch fist bump" },
  { ch: "🤛", zh: "左拳", en: "left facing fist" },
  { ch: "🤜", zh: "右拳", en: "right facing fist" },
  { ch: "👏", zh: "鼓掌", en: "clapping hands applause" },
  { ch: "🙌", zh: "举双手", en: "raising hands celebrate" },
  { ch: "👐", zh: "张开双手", en: "open hands" },
  { ch: "🤲", zh: "摊开双手", en: "palms up together" },
  { ch: "🤝", zh: "握手", en: "handshake deal" },
  { ch: "🙏", zh: "祈祷拜托", en: "pray please thanks" },
  { ch: "✍️", zh: "写字", en: "writing hand" },
  { ch: "💅", zh: "美甲", en: "nail polish" },
  { ch: "💪", zh: "肌肉力量", en: "muscle strong flex" },
  { ch: "🦾", zh: "机械臂", en: "mechanical arm" },
  { ch: "🦵", zh: "腿", en: "leg limb" },
  { ch: "🦶", zh: "脚", en: "foot" },
  { ch: "👂", zh: "耳朵", en: "ear listen" },
  { ch: "👃", zh: "鼻子", en: "nose smell" },
  { ch: "🧠", zh: "大脑", en: "brain smart" },
  { ch: "👀", zh: "眼睛看", en: "eyes look" },
  { ch: "👁️", zh: "单眼", en: "eye watching" },
  { ch: "👅", zh: "舌头", en: "tongue taste" },
  { ch: "👄", zh: "嘴唇", en: "mouth lips kiss" },
];

const ANIMALS: EmojiItem[] = [
  { ch: "🐶", zh: "小狗", en: "dog puppy" },
  { ch: "🐱", zh: "小猫", en: "cat kitty" },
  { ch: "🐭", zh: "老鼠", en: "mouse" },
  { ch: "🐹", zh: "仓鼠", en: "hamster" },
  { ch: "🐰", zh: "兔子", en: "rabbit bunny" },
  { ch: "🦊", zh: "狐狸", en: "fox" },
  { ch: "🐻", zh: "熊", en: "bear" },
  { ch: "🐼", zh: "熊猫", en: "panda" },
  { ch: "🐨", zh: "考拉", en: "koala" },
  { ch: "🐯", zh: "老虎", en: "tiger" },
  { ch: "🦁", zh: "狮子", en: "lion" },
  { ch: "🐮", zh: "牛", en: "cow" },
  { ch: "🐷", zh: "猪", en: "pig" },
  { ch: "🐸", zh: "青蛙", en: "frog" },
  { ch: "🐵", zh: "猴子", en: "monkey face" },
  { ch: "🙈", zh: "不看猴子", en: "see no evil monkey" },
  { ch: "🙉", zh: "不听猴子", en: "hear no evil monkey" },
  { ch: "🙊", zh: "不说猴子", en: "speak no evil monkey" },
  { ch: "🐔", zh: "鸡", en: "chicken" },
  { ch: "🐧", zh: "企鹅", en: "penguin" },
  { ch: "🐦", zh: "小鸟", en: "bird" },
  { ch: "🐤", zh: "小鸡", en: "baby chick" },
  { ch: "🦆", zh: "鸭子", en: "duck" },
  { ch: "🦅", zh: "鹰", en: "eagle" },
  { ch: "🦉", zh: "猫头鹰", en: "owl" },
  { ch: "🦇", zh: "蝙蝠", en: "bat" },
  { ch: "🐺", zh: "狼", en: "wolf" },
  { ch: "🐗", zh: "野猪", en: "boar" },
  { ch: "🐴", zh: "马", en: "horse" },
  { ch: "🦄", zh: "独角兽", en: "unicorn" },
  { ch: "🐝", zh: "蜜蜂", en: "bee honey" },
  { ch: "🐛", zh: "毛虫", en: "bug caterpillar" },
  { ch: "🦋", zh: "蝴蝶", en: "butterfly" },
  { ch: "🐌", zh: "蜗牛", en: "snail" },
  { ch: "🐞", zh: "瓢虫", en: "lady beetle" },
  { ch: "🐜", zh: "蚂蚁", en: "ant" },
  { ch: "🕷️", zh: "蜘蛛", en: "spider" },
  { ch: "🦂", zh: "蝎子", en: "scorpion" },
  { ch: "🐢", zh: "乌龟", en: "turtle" },
  { ch: "🐍", zh: "蛇", en: "snake" },
  { ch: "🦎", zh: "蜥蜴", en: "lizard" },
  { ch: "🐙", zh: "章鱼", en: "octopus" },
  { ch: "🦑", zh: "鱿鱼", en: "squid" },
  { ch: "🦐", zh: "虾", en: "shrimp" },
  { ch: "🦀", zh: "螃蟹", en: "crab" },
  { ch: "🐡", zh: "河豚", en: "blowfish" },
  { ch: "🐠", zh: "热带鱼", en: "tropical fish" },
  { ch: "🐟", zh: "鱼", en: "fish" },
  { ch: "🐬", zh: "海豚", en: "dolphin" },
  { ch: "🐳", zh: "鲸鱼", en: "whale" },
  { ch: "🦈", zh: "鲨鱼", en: "shark" },
  { ch: "🐊", zh: "鳄鱼", en: "crocodile" },
  { ch: "🐘", zh: "大象", en: "elephant" },
  { ch: "🦒", zh: "长颈鹿", en: "giraffe" },
  { ch: "🦘", zh: "袋鼠", en: "kangaroo" },
  { ch: "🐫", zh: "骆驼", en: "camel" },
  { ch: "🦙", zh: "羊驼", en: "llama" },
  { ch: "🦥", zh: "树懒", en: "sloth" },
  { ch: "🐿️", zh: "松鼠", en: "squirrel" },
  { ch: "🌵", zh: "仙人掌", en: "cactus" },
  { ch: "🌲", zh: "松树", en: "evergreen tree" },
  { ch: "🌳", zh: "树", en: "deciduous tree" },
  { ch: "🌴", zh: "棕榈树", en: "palm tree" },
  { ch: "🌱", zh: "幼苗", en: "seedling grow" },
  { ch: "🌿", zh: "草", en: "herb grass" },
  { ch: "🍀", zh: "四叶草", en: "clover luck" },
  { ch: "🍁", zh: "枫叶", en: "maple leaf autumn" },
  { ch: "🍂", zh: "落叶", en: "fallen leaves" },
  { ch: "🌸", zh: "樱花", en: "cherry blossom" },
  { ch: "🌹", zh: "玫瑰", en: "rose flower" },
  { ch: "🌻", zh: "向日葵", en: "sunflower" },
  { ch: "🌈", zh: "彩虹", en: "rainbow" },
  { ch: "⭐", zh: "星星", en: "star" },
  { ch: "✨", zh: "闪亮", en: "sparkles shine" },
  { ch: "⚡", zh: "闪电", en: "lightning bolt" },
  { ch: "🔥", zh: "火焰", en: "fire flame hot" },
  { ch: "💧", zh: "水滴", en: "droplet water" },
  { ch: "🌊", zh: "海浪", en: "ocean wave" },
  { ch: "❄️", zh: "雪花", en: "snowflake snow" },
  { ch: "☔", zh: "雨伞", en: "umbrella rain" },
];

const FOOD: EmojiItem[] = [
  { ch: "🍏", zh: "青苹果", en: "green apple" },
  { ch: "🍎", zh: "红苹果", en: "red apple" },
  { ch: "🍐", zh: "梨", en: "pear" },
  { ch: "🍊", zh: "橘子", en: "orange tangerine" },
  { ch: "🍋", zh: "柠檬", en: "lemon" },
  { ch: "🍌", zh: "香蕉", en: "banana" },
  { ch: "🍉", zh: "西瓜", en: "watermelon" },
  { ch: "🍇", zh: "葡萄", en: "grapes" },
  { ch: "🍓", zh: "草莓", en: "strawberry" },
  { ch: "🫐", zh: "蓝莓", en: "blueberries" },
  { ch: "🍈", zh: "甜瓜", en: "melon" },
  { ch: "🍒", zh: "樱桃", en: "cherries" },
  { ch: "🍑", zh: "桃子", en: "peach" },
  { ch: "🥭", zh: "芒果", en: "mango" },
  { ch: "🍍", zh: "菠萝", en: "pineapple" },
  { ch: "🥥", zh: "椰子", en: "coconut" },
  { ch: "🥝", zh: "猕猴桃", en: "kiwi fruit" },
  { ch: "🍅", zh: "番茄", en: "tomato" },
  { ch: "🍆", zh: "茄子", en: "eggplant" },
  { ch: "🥑", zh: "牛油果", en: "avocado" },
  { ch: "🥦", zh: "西兰花", en: "broccoli" },
  { ch: "🥬", zh: "青菜", en: "leafy green" },
  { ch: "🥒", zh: "黄瓜", en: "cucumber" },
  { ch: "🌶️", zh: "辣椒", en: "hot pepper spicy" },
  { ch: "🌽", zh: "玉米", en: "corn" },
  { ch: "🥕", zh: "胡萝卜", en: "carrot" },
  { ch: "🍞", zh: "面包", en: "bread loaf" },
  { ch: "🥐", zh: "牛角面包", en: "croissant" },
  { ch: "🥖", zh: "法棍", en: "baguette" },
  { ch: "🧀", zh: "奶酪", en: "cheese" },
  { ch: "🥚", zh: "鸡蛋", en: "egg" },
  { ch: "🍳", zh: "煎蛋", en: "fried egg cooking" },
  { ch: "🥞", zh: "松饼", en: "pancakes" },
  { ch: "🧇", zh: "华夫饼", en: "waffle" },
  { ch: "🍕", zh: "披萨", en: "pizza" },
  { ch: "🍔", zh: "汉堡", en: "hamburger burger" },
  { ch: "🍟", zh: "薯条", en: "french fries" },
  { ch: "🌭", zh: "热狗", en: "hot dog" },
  { ch: "🥪", zh: "三明治", en: "sandwich" },
  { ch: "🌮", zh: "墨西哥卷饼", en: "taco" },
  { ch: "🍜", zh: "拉面", en: "ramen noodles" },
  { ch: "🍚", zh: "米饭", en: "cooked rice" },
  { ch: "🍣", zh: "寿司", en: "sushi" },
  { ch: "🍱", zh: "便当", en: "bento box" },
  { ch: "🍛", zh: "咖喱饭", en: "curry rice" },
  { ch: "🍗", zh: "鸡腿", en: "poultry leg chicken" },
  { ch: "🍖", zh: "肉", en: "meat bone" },
  { ch: "🍤", zh: "炸虾", en: "fried shrimp" },
  { ch: "🍦", zh: "冰淇淋", en: "ice cream soft serve" },
  { ch: "🍰", zh: "蛋糕", en: "cake slice shortcake" },
  { ch: "🎂", zh: "生日蛋糕", en: "birthday cake" },
  { ch: "🧁", zh: "纸杯蛋糕", en: "cupcake" },
  { ch: "🍫", zh: "巧克力", en: "chocolate bar" },
  { ch: "🍩", zh: "甜甜圈", en: "doughnut donut" },
  { ch: "🍪", zh: "饼干", en: "cookie biscuit" },
  { ch: "🍬", zh: "糖果", en: "candy sweet" },
  { ch: "🍭", zh: "棒棒糖", en: "lollipop" },
  { ch: "🍯", zh: "蜂蜜", en: "honey pot" },
  { ch: "☕", zh: "咖啡热饮", en: "coffee hot beverage" },
  { ch: "🍵", zh: "茶", en: "tea green tea" },
  { ch: "🧋", zh: "珍珠奶茶", en: "bubble tea boba" },
  { ch: "🥤", zh: "饮料杯", en: "cup straw drink" },
  { ch: "🍺", zh: "啤酒", en: "beer mug" },
  { ch: "🍻", zh: "干杯啤酒", en: "beer cheers clink" },
  { ch: "🍷", zh: "红酒", en: "wine glass" },
  { ch: "🍸", zh: "鸡尾酒", en: "cocktail martini" },
  { ch: "🍾", zh: "香槟", en: "champagne pop bottle" },
  { ch: "🥂", zh: "干杯", en: "clinking glasses toast" },
];

const ACTIVITIES: EmojiItem[] = [
  { ch: "⚽", zh: "足球", en: "soccer football" },
  { ch: "🏀", zh: "篮球", en: "basketball" },
  { ch: "🏈", zh: "美式橄榄球", en: "american football" },
  { ch: "⚾", zh: "棒球", en: "baseball" },
  { ch: "🎾", zh: "网球", en: "tennis" },
  { ch: "🏐", zh: "排球", en: "volleyball" },
  { ch: "🏉", zh: "英式橄榄球", en: "rugby football" },
  { ch: "🎱", zh: "台球", en: "billiards pool 8 ball" },
  { ch: "🏓", zh: "乒乓球", en: "ping pong table tennis" },
  { ch: "🏸", zh: "羽毛球", en: "badminton" },
  { ch: "🏒", zh: "冰球", en: "ice hockey" },
  { ch: "⛳", zh: "高尔夫", en: "golf flag hole" },
  { ch: "🏹", zh: "射箭", en: "bow arrow archery" },
  { ch: "🎣", zh: "钓鱼", en: "fishing" },
  { ch: "🥊", zh: "拳击", en: "boxing glove" },
  { ch: "🥋", zh: "武术", en: "martial arts uniform" },
  { ch: "⛸️", zh: "滑冰", en: "ice skate" },
  { ch: "🎿", zh: "滑雪", en: "ski skis" },
  { ch: "🏂", zh: "单板滑雪", en: "snowboarder" },
  { ch: "🪂", zh: "跳伞", en: "parachute" },
  { ch: "🏋️", zh: "举重", en: "weight lifting" },
  { ch: "🤸", zh: "侧手翻", en: "cartwheel gymnastics" },
  { ch: "🏊", zh: "游泳", en: "swimming swimmer" },
  { ch: "🚴", zh: "骑自行车", en: "biking cyclist" },
  { ch: "🏄", zh: "冲浪", en: "surfing surfer" },
  { ch: "🎮", zh: "游戏手柄", en: "video game controller" },
  { ch: "🕹️", zh: "摇杆", en: "joystick arcade" },
  { ch: "🎲", zh: "骰子", en: "dice game die" },
  { ch: "🧩", zh: "拼图", en: "puzzle piece" },
  { ch: "🎯", zh: "靶心", en: "dart bullseye target" },
  { ch: "🎳", zh: "保龄球", en: "bowling" },
  { ch: "🎭", zh: "戏剧", en: "performing arts theater" },
  { ch: "🎨", zh: "调色盘", en: "art palette paint" },
  { ch: "🎬", zh: "场记板", en: "clapper board movie" },
  { ch: "🎤", zh: "麦克风", en: "microphone sing karaoke" },
  { ch: "🎧", zh: "耳机", en: "headphone music" },
  { ch: "🎼", zh: "乐谱", en: "musical score" },
  { ch: "🎹", zh: "钢琴键盘", en: "piano keyboard" },
  { ch: "🥁", zh: "鼓", en: "drum" },
  { ch: "🎸", zh: "吉他", en: "guitar" },
  { ch: "🎻", zh: "小提琴", en: "violin" },
  { ch: "🎺", zh: "小号", en: "trumpet" },
  { ch: "🎫", zh: "门票", en: "ticket admission" },
  { ch: "🏆", zh: "奖杯", en: "trophy winner" },
  { ch: "🥇", zh: "金牌", en: "gold medal first" },
  { ch: "🥈", zh: "银牌", en: "silver medal second" },
  { ch: "🥉", zh: "铜牌", en: "bronze medal third" },
  { ch: "🏅", zh: "奖牌", en: "medal award" },
  { ch: "🎪", zh: "马戏团", en: "circus tent" },
];

const TRAVEL: EmojiItem[] = [
  { ch: "🚗", zh: "汽车", en: "car automobile" },
  { ch: "🚕", zh: "出租车", en: "taxi cab" },
  { ch: "🚙", zh: "越野车", en: "sport utility vehicle" },
  { ch: "🚌", zh: "公交车", en: "bus" },
  { ch: "🏎️", zh: "赛车", en: "racing car formula" },
  { ch: "🚑", zh: "救护车", en: "ambulance" },
  { ch: "🚒", zh: "消防车", en: "fire engine truck" },
  { ch: "🚚", zh: "货车", en: "delivery truck" },
  { ch: "🚜", zh: "拖拉机", en: "tractor farm" },
  { ch: "🛵", zh: "摩托踏板车", en: "motor scooter" },
  { ch: "🏍️", zh: "摩托车", en: "motorcycle" },
  { ch: "🚲", zh: "自行车", en: "bicycle bike" },
  { ch: "🚨", zh: "警灯", en: "police car light siren" },
  { ch: "🚦", zh: "红绿灯", en: "traffic light" },
  { ch: "🚧", zh: "施工路障", en: "construction barrier" },
  { ch: "⛽", zh: "加油站", en: "fuel gas station pump" },
  { ch: "🚂", zh: "火车头", en: "locomotive train" },
  { ch: "🚄", zh: "高铁", en: "high speed train bullet" },
  { ch: "🚅", zh: "动车", en: "bullet train" },
  { ch: "🚇", zh: "地铁", en: "metro subway" },
  { ch: "🚉", zh: "车站", en: "station train stop" },
  { ch: "✈️", zh: "飞机", en: "airplane flight plane" },
  { ch: "🛫", zh: "起飞", en: "flight departure takeoff" },
  { ch: "🛬", zh: "降落", en: "flight arrival landing" },
  { ch: "🚁", zh: "直升机", en: "helicopter" },
  { ch: "🚀", zh: "火箭", en: "rocket launch ship" },
  { ch: "🛸", zh: "飞碟", en: "flying saucer ufo" },
  { ch: "⛵", zh: "帆船", en: "sailboat" },
  { ch: "🚤", zh: "快艇", en: "speedboat" },
  { ch: "🛳️", zh: "客轮", en: "passenger ship liner" },
  { ch: "⚓", zh: "锚", en: "anchor" },
  { ch: "🗺️", zh: "世界地图", en: "world map" },
  { ch: "🗽", zh: "自由女神像", en: "statue of liberty" },
  { ch: "🏰", zh: "城堡", en: "castle european" },
  { ch: "🏯", zh: "日式城堡", en: "japanese castle" },
  { ch: "🗼", zh: "东京塔", en: "tokyo tower" },
  { ch: "🎡", zh: "摩天轮", en: "ferris wheel" },
  { ch: "🎢", zh: "过山车", en: "roller coaster" },
  { ch: "⛲", zh: "喷泉", en: "fountain" },
  { ch: "🏖️", zh: "海滩", en: "beach umbrella sand" },
  { ch: "🏝️", zh: "荒岛", en: "desert island" },
  { ch: "🏜️", zh: "沙漠", en: "desert cactus" },
  { ch: "🌋", zh: "火山", en: "volcano erupting" },
  { ch: "⛰️", zh: "山", en: "mountain" },
  { ch: "🏔️", zh: "雪山", en: "snow capped mountain" },
  { ch: "🏕️", zh: "露营", en: "camping tent" },
  { ch: "🏠", zh: "房子", en: "house home" },
  { ch: "🏢", zh: "办公楼", en: "office building" },
  { ch: "🏥", zh: "医院", en: "hospital" },
  { ch: "🏦", zh: "银行", en: "bank" },
  { ch: "🏨", zh: "酒店", en: "hotel" },
  { ch: "🏪", zh: "便利店", en: "convenience store" },
  { ch: "🏫", zh: "学校", en: "school" },
  { ch: "⛪", zh: "教堂", en: "church" },
  { ch: "🌆", zh: "城市黄昏", en: "cityscape dusk" },
  { ch: "🌃", zh: "夜景", en: "night with stars city" },
  { ch: "🌉", zh: "桥夜景", en: "bridge at night" },
];

const OBJECTS: EmojiItem[] = [
  { ch: "⌚", zh: "手表", en: "watch wristwatch" },
  { ch: "📱", zh: "手机", en: "mobile phone smartphone" },
  { ch: "💻", zh: "笔记本电脑", en: "laptop computer" },
  { ch: "🖥️", zh: "台式电脑", en: "desktop computer" },
  { ch: "⌨️", zh: "键盘", en: "keyboard" },
  { ch: "🖱️", zh: "鼠标", en: "computer mouse" },
  { ch: "🖨️", zh: "打印机", en: "printer" },
  { ch: "💾", zh: "软盘", en: "floppy disk save" },
  { ch: "💿", zh: "光盘", en: "optical disc cd" },
  { ch: "📷", zh: "相机", en: "camera photo" },
  { ch: "📹", zh: "摄像机", en: "video camera" },
  { ch: "🎥", zh: "摄影机", en: "movie camera film" },
  { ch: "📺", zh: "电视", en: "television tv" },
  { ch: "📻", zh: "收音机", en: "radio" },
  { ch: "🎙️", zh: "录音麦克风", en: "studio microphone" },
  { ch: "🔍", zh: "放大镜左", en: "magnifying glass left search" },
  { ch: "🔎", zh: "放大镜右", en: "magnifying glass right" },
  { ch: "💡", zh: "灯泡", en: "light bulb idea" },
  { ch: "🔦", zh: "手电筒", en: "flashlight torch" },
  { ch: "🕯️", zh: "蜡烛", en: "candle" },
  { ch: "📔", zh: "笔记本装饰", en: "notebook decorative cover" },
  { ch: "📖", zh: "打开的书", en: "open book reading" },
  { ch: "📚", zh: "书堆", en: "books stack" },
  { ch: "📝", zh: "备忘录", en: "memo note pencil" },
  { ch: "📄", zh: "文件页", en: "page facing up document" },
  { ch: "📰", zh: "报纸", en: "newspaper news" },
  { ch: "📅", zh: "日历", en: "calendar date" },
  { ch: "📆", zh: "撕页日历", en: "tear off calendar" },
  { ch: "📇", zh: "名片盒", en: "card index" },
  { ch: "📈", zh: "上涨图表", en: "chart increasing up" },
  { ch: "📉", zh: "下跌图表", en: "chart decreasing down" },
  { ch: "📊", zh: "柱状图", en: "bar chart" },
  { ch: "📋", zh: "剪贴板", en: "clipboard" },
  { ch: "📌", zh: "图钉", en: "pushpin pin" },
  { ch: "📎", zh: "回形针", en: "paperclip" },
  { ch: "✂️", zh: "剪刀", en: "scissors cut" },
  { ch: "📐", zh: "三角板", en: "triangular ruler" },
  { ch: "📏", zh: "直尺", en: "straight ruler measure" },
  { ch: "🔒", zh: "上锁", en: "locked lock" },
  { ch: "🔓", zh: "开锁", en: "unlocked open" },
  { ch: "🔑", zh: "钥匙", en: "key" },
  { ch: "🔨", zh: "锤子", en: "hammer tool" },
  { ch: "🪛", zh: "螺丝刀", en: "screwdriver" },
  { ch: "🔧", zh: "扳手", en: "wrench spanner fix" },
  { ch: "⚙️", zh: "齿轮", en: "gear settings" },
  { ch: "🧲", zh: "磁铁", en: "magnet" },
  { ch: "🧪", zh: "试管", en: "test tube lab" },
  { ch: "🔬", zh: "显微镜", en: "microscope science" },
  { ch: "🔭", zh: "望远镜", en: "telescope astronomy" },
  { ch: "📡", zh: "卫星天线", en: "satellite antenna dish" },
  { ch: "💉", zh: "注射器", en: "syringe needle shot" },
  { ch: "💊", zh: "药丸", en: "pill medicine" },
  { ch: "🩹", zh: "创可贴", en: "adhesive bandage" },
  { ch: "🧹", zh: "扫帚", en: "broom sweep" },
  { ch: "🧺", zh: "篮子", en: "basket laundry" },
  { ch: "🛒", zh: "购物车", en: "shopping cart" },
  { ch: "🎁", zh: "礼物", en: "gift present box" },
  { ch: "🎈", zh: "气球", en: "balloon party" },
  { ch: "🎉", zh: "拉炮庆祝", en: "party popper celebrate" },
  { ch: " confetti", zh: "撒花", en: "confetti ball" },
  { ch: "🧸", zh: "玩具熊", en: "teddy bear toy" },
  { ch: "⏰", zh: "闹钟", en: "alarm clock time" },
  { ch: "⏳", zh: "沙漏", en: "hourglass time flowing" },
  { ch: "🔋", zh: "电池", en: "battery power" },
  { ch: "🔌", zh: "插头", en: "electric plug power" },
  { ch: "🧭", zh: "指南针", en: "compass navigate" },
  { ch: "🌡️", zh: "温度计", en: "thermometer temperature" },
];

const SYMBOLS: EmojiItem[] = [
  { ch: "❤️", zh: "红心", en: "red heart love" },
  { ch: "🧡", zh: "橙心", en: "orange heart" },
  { ch: "💛", zh: "黄心", en: "yellow heart" },
  { ch: "💚", zh: "绿心", en: "green heart" },
  { ch: "💙", zh: "蓝心", en: "blue heart" },
  { ch: "💜", zh: "紫心", en: "purple heart" },
  { ch: "🖤", zh: "黑心", en: "black heart" },
  { ch: "🤍", zh: "白心", en: "white heart" },
  { ch: "💔", zh: "心碎", en: "broken heart" },
  { ch: "💕", zh: "双心", en: "two hearts" },
  { ch: "💞", zh: "旋转心", en: "revolving hearts" },
  { ch: "💓", zh: "跳动心", en: "beating heart" },
  { ch: "💗", zh: "变大的心", en: "growing heart" },
  { ch: "💖", zh: "闪亮心", en: "sparkling heart" },
  { ch: "💘", zh: "爱心箭", en: "heart with arrow cupid" },
  { ch: "💝", zh: "缎带心礼盒", en: "heart with ribbon gift" },
  { ch: "☮️", zh: "和平符号", en: "peace symbol" },
  { ch: "☯️", zh: "阴阳", en: "yin yang taiji" },
  { ch: "♈", zh: "白羊座", en: "aries zodiac" },
  { ch: "♉", zh: "金牛座", en: "taurus zodiac" },
  { ch: "♊", zh: "双子座", en: "gemini zodiac" },
  { ch: "♋", zh: "巨蟹座", en: "cancer zodiac" },
  { ch: "♌", zh: "狮子座", en: "leo zodiac" },
  { ch: "♍", zh: "处女座", en: "virgo zodiac" },
  { ch: "♎", zh: "天秤座", en: "libra zodiac" },
  { ch: "♏", zh: "天蝎座", en: "scorpio zodiac" },
  { ch: "♐", zh: "射手座", en: "sagittarius zodiac" },
  { ch: "♑", zh: "摩羯座", en: "capricorn zodiac" },
  { ch: "♒", zh: "水瓶座", en: "aquarius zodiac" },
  { ch: "♓", zh: "双鱼座", en: "pisces zodiac" },
  { ch: "✅", zh: "打勾", en: "check mark button yes done" },
  { ch: "❌", zh: "叉号", en: "cross mark no wrong" },
  { ch: "❗", zh: "感叹号", en: "exclamation mark important" },
  { ch: "❓", zh: "问号", en: "question mark" },
  { ch: "⚠️", zh: "警告", en: "warning caution" },
  { ch: "🚫", zh: "禁止", en: "prohibited no entry" },
  { ch: "♻️", zh: "回收", en: "recycle symbol" },
  { ch: "💯", zh: "百分百", en: "hundred points score perfect" },
  { ch: "🔞", zh: "十八禁", en: "no one under eighteen" },
  { ch: "⚛️", zh: "原子", en: "atom symbol science" },
  { ch: "☢️", zh: "放射性", en: "radioactive" },
  { ch: "©️", zh: "版权", en: "copyright" },
  { ch: "®️", zh: "注册商标", en: "registered" },
  { ch: "™️", zh: "商标", en: "trademark tm" },
  { ch: "🌐", zh: "地球网络", en: "globe with meridians web" },
  { ch: "⚜️", zh: "百合花饰", en: "fleur de lis" },
  { ch: "🔱", zh: "三叉戟", en: "trident emblem" },
  { ch: "🔔", zh: "铃铛", en: "bell notification" },
  { ch: "🔕", zh: "静音铃", en: "bell with slash mute" },
];

const FLAGS: EmojiItem[] = [
  { ch: "🏁", zh: "方格旗", en: "chequered flag finish" },
  { ch: "🚩", zh: "红旗三角", en: "triangular flag" },
  { ch: "🎌", zh: "日本交叉旗", en: "crossed flags" },
  { ch: "🏳️", zh: "白旗", en: "white flag surrender" },
  { ch: "🏳️‍🌈", zh: "彩虹旗", en: "rainbow flag pride" },
  { ch: "🏴‍☠️", zh: "海盗旗", en: "pirate flag jolly roger" },
  { ch: "🇨🇳", zh: "中国国旗", en: "china flag" },
  { ch: "🇭🇰", zh: "香港区旗", en: "hong kong flag" },
  { ch: "🇲🇴", zh: "澳门区旗", en: "macau flag" },
  { ch: "🇹🇼", zh: "台湾地区旗", en: "taiwan flag" },
  { ch: "🇯🇵", zh: "日本国旗", en: "japan flag" },
  { ch: "🇰🇷", zh: "韩国国旗", en: "south korea flag" },
  { ch: "🇺🇸", zh: "美国国旗", en: "united states flag usa" },
  { ch: "🇬🇧", zh: "英国国旗", en: "united kingdom flag uk" },
  { ch: "🇫🇷", zh: "法国国旗", en: "france flag" },
  { ch: "🇩🇪", zh: "德国国旗", en: "germany flag" },
  { ch: "🇮🇹", zh: "意大利国旗", en: "italy flag" },
  { ch: "🇪🇸", zh: "西班牙国旗", en: "spain flag" },
  { ch: "🇵🇹", zh: "葡萄牙国旗", en: "portugal flag" },
  { ch: "🇷🇺", zh: "俄罗斯国旗", en: "russia flag" },
  { ch: "🇮🇳", zh: "印度国旗", en: "india flag" },
  { ch: "🇧🇷", zh: "巴西国旗", en: "brazil flag" },
  { ch: "🇨🇦", zh: "加拿大国旗", en: "canada flag" },
  { ch: "🇦🇺", zh: "澳大利亚国旗", en: "australia flag" },
  { ch: "🇳🇿", zh: "新西兰国旗", en: "new zealand flag" },
  { ch: "🇸🇬", zh: "新加坡国旗", en: "singapore flag" },
  { ch: "🇲🇾", zh: "马来西亚国旗", en: "malaysia flag" },
  { ch: "🇹🇭", zh: "泰国国旗", en: "thailand flag" },
  { ch: "🇻🇳", zh: "越南国旗", en: "vietnam flag" },
  { ch: "🇮🇩", zh: "印尼国旗", en: "indonesia flag" },
  { ch: "🇵🇭", zh: "菲律宾国旗", en: "philippines flag" },
  { ch: "🇸🇦", zh: "沙特国旗", en: "saudi arabia flag" },
  { ch: "🇦🇪", zh: "阿联酋国旗", en: "united arab emirates flag" },
  { ch: "🇪🇬", zh: "埃及国旗", en: "egypt flag" },
  { ch: "🇿🇦", zh: "南非国旗", en: "south africa flag" },
  { ch: "🇳🇬", zh: "尼日利亚国旗", en: "nigeria flag" },
  { ch: "🇦🇷", zh: "阿根廷国旗", en: "argentina flag" },
  { ch: "🇲🇽", zh: "墨西哥国旗", en: "mexico flag" },
  { ch: "🇨🇭", zh: "瑞士国旗", en: "switzerland flag" },
  { ch: "🇳🇱", zh: "荷兰国旗", en: "netherlands flag" },
  { ch: "🇸🇪", zh: "瑞典国旗", en: "sweden flag" },
  { ch: "🇳🇴", zh: "挪威国旗", en: "norway flag" },
  { ch: "🇩🇰", zh: "丹麦国旗", en: "denmark flag" },
  { ch: "🇫🇮", zh: "芬兰国旗", en: "finland flag" },
  { ch: "🇵🇱", zh: "波兰国旗", en: "poland flag" },
  { ch: "🇺🇦", zh: "乌克兰国旗", en: "ukraine flag" },
  { ch: "🇬🇷", zh: "希腊国旗", en: "greece flag" },
  { ch: "🇹🇷", zh: "土耳其国旗", en: "turkey flag" },
  { ch: "🇮🇱", zh: "以色列国旗", en: "israel flag" },
  { ch: "🇵🇰", zh: "巴基斯坦国旗", en: "pakistan flag" },
  { ch: "🇧🇩", zh: "孟加拉国旗", en: "bangladesh flag" },
  { ch: "🇱🇰", zh: "斯里兰卡国旗", en: "sri lanka flag" },
];

/** 面板 emoji 分类（顺序即侧栏顺序）。 */
export const EMOJI_CATEGORIES: EmojiCategory[] = [
  { id: "smileys", zh: "笑脸与情感", en: "Smileys", icon: "😀", items: SMILEYS },
  { id: "gestures", zh: "手势与人物", en: "Gestures", icon: "👋", items: GESTURES },
  { id: "animals", zh: "动物与自然", en: "Animals", icon: "🐶", items: ANIMALS },
  { id: "food", zh: "食物与饮料", en: "Food", icon: "🍎", items: FOOD },
  { id: "activities", zh: "活动与运动", en: "Activities", icon: "⚽", items: ACTIVITIES },
  { id: "travel", zh: "旅行与地点", en: "Travel", icon: "🚗", items: TRAVEL },
  { id: "objects", zh: "物品", en: "Objects", icon: "💡", items: OBJECTS },
  { id: "symbols", zh: "符号", en: "Symbols", icon: "❤️", items: SYMBOLS },
  { id: "flags", zh: "旗帜", en: "Flags", icon: "🏁", items: FLAGS },
];

// ---------- 常用符号区（数学 / 货币 / 箭头 / 制表） ----------

export interface SymbolGroup {
  id: "math" | "currency" | "arrow" | "box";
  zh: string;
  en: string;
  items: EmojiItem[];
}

export const SYMBOL_GROUPS: SymbolGroup[] = [
  {
    id: "math",
    zh: "数学",
    en: "Math",
    items: [
      { ch: "+", zh: "加号", en: "plus add" },
      { ch: "−", zh: "减号", en: "minus subtract" },
      { ch: "×", zh: "乘号", en: "multiply times" },
      { ch: "÷", zh: "除号", en: "divide division" },
      { ch: "=", zh: "等号", en: "equals equal" },
      { ch: "≠", zh: "不等号", en: "not equal" },
      { ch: "≈", zh: "约等于", en: "approximately equal" },
      { ch: "≤", zh: "小于等于", en: "less or equal" },
      { ch: "≥", zh: "大于等于", en: "greater or equal" },
      { ch: "±", zh: "正负号", en: "plus minus" },
      { ch: "∓", zh: "负正号", en: "minus plus" },
      { ch: "∞", zh: "无穷", en: "infinity infinite" },
      { ch: "√", zh: "根号", en: "square root radical" },
      { ch: "∑", zh: "求和", en: "summation sigma sum" },
      { ch: "∏", zh: "求积", en: "product pi" },
      { ch: "∫", zh: "积分", en: "integral" },
      { ch: "∂", zh: "偏微分", en: "partial derivative" },
      { ch: "∈", zh: "属于", en: "element of in set" },
      { ch: "∉", zh: "不属于", en: "not element of" },
      { ch: "∪", zh: "并集", en: "union set" },
      { ch: "∩", zh: "交集", en: "intersection set" },
      { ch: "∀", zh: "任意全称", en: "for all universal" },
      { ch: "∃", zh: "存在", en: "there exists" },
      { ch: "∅", zh: "空集", en: "empty set null" },
      { ch: "°", zh: "度数符号", en: "degree sign" },
      { ch: "′", zh: "分撇号", en: "prime minute" },
      { ch: "″", zh: "秒双撇号", en: "double prime second" },
    ],
  },
  {
    id: "currency",
    zh: "货币",
    en: "Currency",
    items: [
      { ch: "$", zh: "美元符号", en: "dollar sign usd" },
      { ch: "¥", zh: "人民币日元符号", en: "yen yuan sign cny jpy" },
      { ch: "€", zh: "欧元符号", en: "euro sign eur" },
      { ch: "£", zh: "英镑符号", en: "pound sign gbp" },
      { ch: "₩", zh: "韩元符号", en: "won sign krw" },
      { ch: "₽", zh: "卢布符号", en: "ruble sign rub" },
      { ch: "₹", zh: "卢比符号", en: "rupee sign inr" },
      { ch: "₿", zh: "比特币符号", en: "bitcoin sign btc" },
      { ch: "¢", zh: "美分符号", en: "cent sign" },
      { ch: "₫", zh: "越南盾符号", en: "dong sign vnd" },
      { ch: "₴", zh: "格里夫纳符号", en: "hryvnia sign uah" },
      { ch: "₺", zh: "里拉符号", en: "lira sign try" },
      { ch: "₦", zh: "奈拉符号", en: "naira sign ngn" },
      { ch: "₱", zh: "比索符号", en: "peso sign php" },
      { ch: "₲", zh: "瓜拉尼符号", en: "guarani sign pyg" },
      { ch: "₡", zh: "科朗符号", en: "colon sign crc" },
      { ch: "¤", zh: "通用货币符号", en: "currency sign generic" },
    ],
  },
  {
    id: "arrow",
    zh: "箭头",
    en: "Arrows",
    items: [
      { ch: "←", zh: "左箭头", en: "left arrow" },
      { ch: "↑", zh: "上箭头", en: "up arrow" },
      { ch: "→", zh: "右箭头", en: "right arrow" },
      { ch: "↓", zh: "下箭头", en: "down arrow" },
      { ch: "↔", zh: "左右箭头", en: "left right arrow" },
      { ch: "↕", zh: "上下箭头", en: "up down arrow" },
      { ch: "↖", zh: "左上箭头", en: "up left arrow" },
      { ch: "↗", zh: "右上箭头", en: "up right arrow" },
      { ch: "↘", zh: "右下箭头", en: "down right arrow" },
      { ch: "↙", zh: "左下箭头", en: "down left arrow" },
      { ch: "⇐", zh: "双线左箭头", en: "double left arrow" },
      { ch: "⇒", zh: "双线右箭头", en: "double right arrow" },
      { ch: "⇔", zh: "双线左右箭头", en: "double left right arrow" },
      { ch: "⇑", zh: "双线上箭头", en: "double up arrow" },
      { ch: "⇓", zh: "双线下箭头", en: "double down arrow" },
      { ch: "➜", zh: "粗右箭头", en: "heavy right arrow" },
      { ch: "⟵", zh: "长左箭头", en: "long left arrow" },
      { ch: "⟶", zh: "长右箭头", en: "long right arrow" },
      { ch: "⟷", zh: "长左右箭头", en: "long left right arrow" },
      { ch: "⤒", zh: "到顶箭头", en: "up to bar arrow" },
      { ch: "⤓", zh: "到底箭头", en: "down to bar arrow" },
      { ch: "⇄", zh: "循环左右箭头", en: "right arrow over left" },
    ],
  },
  {
    id: "box",
    zh: "制表符",
    en: "Box drawing",
    items: [
      { ch: "─", zh: "横线细", en: "light horizontal" },
      { ch: "│", zh: "竖线细", en: "light vertical" },
      { ch: "┌", zh: "左上角", en: "top left corner" },
      { ch: "┐", zh: "右上角", en: "top right corner" },
      { ch: "└", zh: "左下角", en: "bottom left corner" },
      { ch: "┘", zh: "右下角", en: "bottom right corner" },
      { ch: "├", zh: "左丁字", en: "tee right light" },
      { ch: "┤", zh: "右丁字", en: "tee left light" },
      { ch: "┬", zh: "上丁字", en: "tee down light" },
      { ch: "┴", zh: "下丁字", en: "tee up light" },
      { ch: "┼", zh: "十字细", en: "cross light" },
      { ch: "━", zh: "横线粗", en: "heavy horizontal" },
      { ch: "┃", zh: "竖线粗", en: "heavy vertical" },
      { ch: "┏", zh: "粗左上角", en: "heavy top left" },
      { ch: "┓", zh: "粗右上角", en: "heavy top right" },
      { ch: "┗", zh: "粗左下角", en: "heavy bottom left" },
      { ch: "┛", zh: "粗右下角", en: "heavy bottom right" },
      { ch: "┣", zh: "粗左丁字", en: "heavy tee right" },
      { ch: "┫", zh: "粗右丁字", en: "heavy tee left" },
      { ch: "┳", zh: "粗上丁字", en: "heavy tee down" },
      { ch: "┻", zh: "粗下丁字", en: "heavy tee up" },
      { ch: "╋", zh: "粗十字", en: "heavy cross" },
      { ch: "═", zh: "双横线", en: "double horizontal" },
      { ch: "║", zh: "双竖线", en: "double vertical" },
      { ch: "╔", zh: "双左上角", en: "double top left" },
      { ch: "╗", zh: "双右上角", en: "double top right" },
      { ch: "╚", zh: "双左下角", en: "double bottom left" },
      { ch: "╝", zh: "双右下角", en: "double bottom right" },
      { ch: "╠", zh: "双左丁字", en: "double tee right" },
      { ch: "╣", zh: "双右丁字", en: "double tee left" },
      { ch: "╦", zh: "双上丁字", en: "double tee down" },
      { ch: "╩", zh: "双下丁字", en: "double tee up" },
      { ch: "╬", zh: "双十字", en: "double cross" },
    ],
  },
];

/** 全部条目（emoji 分类 + 符号区）展平，供搜索遍历。 */
export const ALL_ITEMS: EmojiItem[] = [
  ...EMOJI_CATEGORIES.flatMap((c) => c.items),
  ...SYMBOL_GROUPS.flatMap((g) => g.items),
];

/** 搜索结果渲染上限（防止超长查询拖慢渲染）。 */
export const SEARCH_CAP = 80;

/**
 * 搜索（纯函数）：
 * - 中文（zh / zh-TW）：zh 描述按子串匹配 + emoji 本体命中
 * - 英文（en）：en 描述大小写不敏感子串 + emoji 本体命中
 * - 空白查询返回空数组；结果上限 SEARCH_CAP
 */
export function searchEmoji(q: string, lang: Lang): EmojiItem[] {
  const query = q.trim();
  if (!query) return [];
  const lower = query.toLowerCase();
  const out: EmojiItem[] = [];
  for (const item of ALL_ITEMS) {
    const hit =
      lang === "en"
        ? item.en.toLowerCase().includes(lower) || item.ch.includes(query)
        : item.zh.includes(query) || item.ch.includes(query);
    if (hit) {
      out.push(item);
      if (out.length >= SEARCH_CAP) break;
    }
  }
  return out;
}

// ---------- 最近使用（localStorage，上限 24） ----------

export const RECENT_KEY = "variable:emoji:recent:v1";
export const RECENT_LIMIT = 24;

/** 读取最近使用（损坏数据静默视为空，纯读无副作用）。 */
export function readRecent(): string[] {
  try {
    const raw = localStorage.getItem(RECENT_KEY);
    if (!raw) return [];
    const arr: unknown = JSON.parse(raw);
    if (!Array.isArray(arr)) return [];
    return arr.filter((x): x is string => typeof x === "string").slice(0, RECENT_LIMIT);
  } catch {
    return [];
  }
}

/** 写入最近使用：去重置顶 + 超限淘汰最旧，返回新列表（并落盘）。 */
export function writeRecent(ch: string): string[] {
  const next = [ch, ...readRecent().filter((x) => x !== ch)].slice(0, RECENT_LIMIT);
  try {
    localStorage.setItem(RECENT_KEY, JSON.stringify(next));
  } catch {
    /* 隐私模式等场景写失败不影响功能（返回值已可用于本次会话渲染） */
  }
  return next;
}
