/**
 * E 个性化域本地词典（PersonaStudio）：不改动 i18n/dictionaries.ts（避免并行冲突），
 * 语言信号取 documentElement.lang（App.tsx 设置应用时写入）——与 theme-studio
 * labels.ts 同族惯例（一处一事实：结构复用，词典内容为本域新词）。
 */
import { useEffect, useState } from "react";

export type LaneLang = "zh" | "en";

export function detectLang(): LaneLang {
  if (typeof document === "undefined") return "zh";
  return document.documentElement.lang === "en" ? "en" : "zh";
}

export function useLaneLang(): LaneLang {
  const [lang, setLang] = useState<LaneLang>(detectLang);
  useEffect(() => {
    const ob = new MutationObserver(() => setLang(detectLang()));
    ob.observe(document.documentElement, { attributes: true, attributeFilter: ["lang"] });
    return () => ob.disconnect();
  }, []);
  return lang;
}

export type LaneT = (key: keyof typeof LABELS.zh) => string;

export function makeT(lang: LaneLang): LaneT {
  return (key) => LABELS[lang][key] ?? LABELS.zh[key] ?? key;
}

export const LABELS = {
  zh: {
    studioTitle: "个性化全域 · Persona Studio",
    studioSubtitle: "E1-E8 · 主题/壁纸/图标/指针/声音/开始菜单/字体/动效 —— 三铁律：随时可改 · 随时可退 · 预设+微调",
    close: "关闭",
    // 导航
    navTheme: "主题",
    navThemeTokens: "令牌表",
    navThemePreview: "实时预览编辑器",
    navThemeAuto: "深浅自动切换",
    navThemeExceptions: "每应用例外",
    navWallpaper: "壁纸",
    navIcons: "图标包",
    navPointer: "指针编辑器",
    navSound: "声音混合器",
    navStart: "开始菜单预设",
    navFont: "字体安全档",
    navMotion: "动效强度预演",
    navArchive: "我的档案",
    navWidgets: "桌面小组件",
    navLock: "锁屏定制",
    navBoot: "开机动画",
    navIme: "输入法皮肤",
    navCtx: "右键菜单",
    navTaskbar: "任务栏",
    navShortcuts: "快捷键",
    navVerdict: "域总检",
    // 通用
    apply: "应用",
    applied: "已应用",
    discard: "放弃更改",
    reset: "恢复默认",
    save: "保存",
    saved: "已保存",
    on: "开",
    off: "关",
    enabled: "启用",
    disabled: "停用",
    unappliedChanges: "有未应用的更改",
    dirtyBannerHint: "应用后全桌生效（300ms 交叉淡入，无重启）；放弃则逐令牌回滚、零残留",
    hashVerified: "哈希还原验证通过（零残留）",
    latencyOk: "改-预览延迟达标（≤100ms）",
    latencyOver: "改-预览延迟超预算",
    previewScene: "预览场景",
    sceneDesktop: "桌面",
    sceneExplorer: "资源管理器",
    sceneSettings: "设置自身",
    restoreThisToken: "恢复此令牌默认",
    coverage: "覆盖度",
    // F151
    tokensTitle: "主题令牌全集（F151）",
    tokensHint: "五类令牌：颜色 24 枚 / 间距六档 / 圆角三档 / 字号四档 / 动效五曲线三时长。语义层改值即时全局热替换——第三方主题作者改这 24 个颜色就能做出完整主题。",
    groupBg: "背景三层",
    groupFg: "前景",
    groupBrand: "强调族",
    groupState: "状态色",
    groupLine: "边框三档",
    groupMisc: "遮罩/悬停/焦点/选区",
    groupSpacing: "间距（乙-1 六档）",
    groupRadius: "圆角（三档）",
    groupFont: "字号（四档）",
    groupMotion: "动效（F124 五曲线三时长）",
    curve: "曲线",
    duration: "时长",
    exportSchema: "导出 JSON Schema",
    // F153
    autoDarkTitle: "深浅自动切换（F153）",
    modeTimer: "按定时",
    modeSunset: "按日落日出",
    darkAt: "进入深色",
    lightAt: "进入浅色",
    sunset: "日落",
    sunrise: "日出",
    pairBinding: "主题对绑定",
    nextSwitch: "下次切换",
    pauseToday: "手动暂停当日",
    skipTonight: "今晚跳过",
    advanceToastTitle: "主题即将切换",
    advanceNow: "立即切换",
    // F162
    exceptionsTitle: "每应用主题例外（F162）",
    exceptionsHint: "上限 10 项；例外应用在全局切换时保持自己的深浅/强调色——共性是默认，个性是特权。",
    addException: "添加例外",
    exceptionMode: "例外模式",
    accentOverride: "强调色覆盖",
    tokenAware: "已接入令牌",
    // F154
    dailyWallTitle: "壁纸每日一换（F154）",
    pool: "图片池",
    changeAt: "更换时刻",
    rotateNow: "现在换一张",
    pinToday: "固定今天这张",
    recentExclude: "近 7 天排除表",
    history: "历史（30 天）",
    // F155
    iconPackTitle: "图标包热更换（F155）",
    installPack: "载入示例包",
    uninstallPack: "还原官方包",
    rollbackPack: "回退上一包",
    coverageLabel: "诚实覆盖度",
    // F156
    pointerTitle: "指针编辑器（F156）",
    hotspot: "热点",
    hotspotUnset: "热点未设（按 (0,0) 运行）",
    scale: "尺寸缩放",
    exportScheme: "导出方案（双倍率 sprite）",
    // F157
    soundTitle: "声音混合器（F157）",
    masterMute: "全部静音（总闸）",
    preview: "试听",
    mutedGlobally: "已全局静音——试听同样无声（总闸语义一致）",
    // F158
    startTitle: "开始菜单布局预设（F158）",
    saveCustom: "保存当前为自定义",
    elderMode: "长辈模式（大图标）",
    fullscreenMode: "全屏开始菜单",
    // F159
    fontTitle: "字体安全档（F159）",
    missingRate: "缺字率",
    verdictOk: "通过",
    verdictWarn: "黄色警告",
    verdictDanger: "红色劝阻",
    forceApply: "我了解缺字影响，强行应用",
    monospace: "等宽",
    // F160
    motionTitle: "动效强度预演（F160）",
    tierFull: "完整",
    tierReduced: "减弱",
    tierOff: "关闭",
    replay: "重播三联",
    a11yNote: "关闭档下动画将瞬显；进度类动画转为显性进度数字（WP-207 无障碍关联）。",
    // F161
    archiveTitle: "我的档案（F161）",
    archiveName: "档案名",
    exportArchive: "导出档案包（vxtheme）",
    importArchive: "导入并复原",
    diffPreview: "差异预览",
    sectionPick: "分节勾选（包是菜单不是套餐）",
    privacyHint: "导出前请检查短语与命名——私人句子可能不想分享。",
    bytes: "字节",
    // F163
    widgetsTitle: "桌面小组件（F163）",
    addWidget: "添加",
    opacity: "透明度",
    clickThrough: "穿透点击",
    // F164
    lockTitle: "锁屏定制（F164）",
    wallpaperFollow: "跟随桌面壁纸",
    wallpaperIndependent: "独立锁屏壁纸",
    showBattery: "状态行·电量",
    showDate: "状态行·日期",
    notifyPrivacy: "通知只计数不显内容",
    // F165
    bootTitle: "开机动画个性化（F165）",
    densityDense: "繁星（1200）",
    densityStandard: "标准（600）",
    densityMinimal: "极简（200）",
    useWallpaperBackdrop: "幕三过渡底图（壁纸暗化 65%）",
    bootInvariant: "结构与时长不可改：8.0s±0.2s（性能契约）",
    // F166
    imeTitle: "输入法皮肤（F166）",
    followTheme: "跟随主题",
    fontSize: "字号（12-16px）",
    candidates: "候选数",
    tryType: "试打：ni hao → 你好，皮肤即改即见",
    // F167
    ctxTitle: "右键菜单自定义（F167）",
    autoSort: "应用注册项按使用频率自动排序",
    restoreDefault: "恢复默认",
    lockedHint: "删除/重命名/属性为系统关键项，锁定不可隐（防自残）。",
    hiddenMore: "隐藏项在「显示更多选项」二级完整保留",
    // F168
    taskbarTitle: "任务栏个性化（F168）",
    iconSize: "图标大小",
    align: "对齐",
    alignCenter: "居中",
    alignLeft: "左对齐",
    autoHide: "自动隐藏（光标贴底 200ms 唤出）",
    // F169
    shortcutsTitle: "快捷键查看器（F169）",
    searchPlaceholder: "搜功能名或按键串…",
    rebind: "重录",
    recording: "按下新组合（Esc 取消）",
    conflictWith: "冲突",
    resetAll: "恢复全部默认",
    // F170
    verdictTitle: "个性化域总检（F170）",
    verdictRun: "执行 19 项三步验收（改→生效→回退）",
    verdictRunning: "执法中…",
    verdictPass: "全绿",
    verdictFail: "存在红项",
    stepMutate: "改",
    stepEffect: "生效",
    stepRollback: "回退",
    evidenceChain: "证据链完整率",
    withinBudget: "30 分钟预算内",
    // 批次四 · 调色板引擎（F151/F154）
    paletteTitle: "壁纸调色板 → 令牌派生",
    paletteExtract: "提取调色板",
    paletteDeriveDark: "派生深色底稿",
    paletteDeriveLight: "派生浅色底稿",
    paletteHarmony: "壁纸 × 主题和谐判定",
    paletteSwatches: "主色簇",
    paletteDerived: "派生底稿（可再微调——不是最终答案）",
    paletteNoAccent: "全灰壁纸——强调色不硬造（诚实覆盖度）",
    // 批次四 · 天文历（F153/F154）
    solarTitle: "日出日落（NOAA 高精度兜底）",
    solarAccuracy: "与 Cooper 兜底对拍",
    solarEqTime: "均时差",
    solarDecl: "太阳赤纬",
    polarDay: "极昼——全天浅色",
    polarNight: "极夜——全天深色",
    preloadTitle: "预载窗口规划",
    preloadPlanOk: "预载计划在位——换图时刻零等待",
    preloadPlanMiss: "无可用空闲窗——沿用昨日壁纸",
    // 批次四 · 图集装箱（F155）
    atlasTitle: "图集装箱计划",
    atlasPages: "图集页",
    atlasOccupancy: "占用率",
    atlasOverflow: "装不下（显性化）",
    atlasSwapBudget: "换包预算拆账",
    atlasWithinBudget: "<2s 预算内",
    // 批次四 · 指针物理（F156）
    cursorPhysicsTitle: "指针跟随物理",
    cursorTrail: "拖尾缓冲",
    cursorSettled: "已收敛（零更新）",
    clickMachine: "点击状态机",
    hotspotTransform: "热点精确变换",
    // 批次四 · 合成实验室（F157）
    synthLabTitle: "PCM 合成实验室",
    synthRender: "渲染并写入 WAV",
    synthPeak: "峰值",
    synthRms: "响度（RMS）",
    synthClipped: "削波样本",
    synthDuration: "时长",
    // 批次四 · 小组件数据（F163）
    widgetDataTitle: "小组件数据引擎",
    freshnessLive: "实时",
    freshnessStale: "已过期",
    freshnessFrozen: "连接中断",
    freshnessNever: "暂无数据",
    nextFetch: "下次拉取",
    jitterNote: "15s 抖动窗——所有组件不同步齐刷（调度风暴免疫）",
    // 批次四 · 锁屏合成（F164）
    lockComposerTitle: "锁屏合成层",
    lockFirstBeat: "第一拍（<100ms 可见）",
    unlockMachine: "解锁状态机",
    unlockCooldown: "冷却中",
    unlockRemaining: "剩余次数",
    blurSpec: "背景虚化参数",
    // 批次四 · 输入法组合（F166）
    imeLabTitle: "拼音组合引擎",
    imeSegments: "音节切分",
    imeCandidatesPage: "候选（第 {p}/{n} 页）",
    imeComposing: "组合期（快捷键已让位）",
    // 批次四 · 菜单与托盘导航（F167/F168）
    ctxNavTitle: "菜单键盘导航",
    ctxTypeAhead: "字母跳转（同字母循环）",
    trayOverflowTitle: "托盘溢出计算",
    trayPinnedOverflow: "钉选被挤出（缺陷级信号）",
    // 批次四 · 序列匹配（F169）
    chordLabTitle: "组合匹配引擎",
    chordPending: "序列缓冲中（1s 内按第二段）",
    chordTimeout: "序列超时作废",
    chordConsistency: "全表一致性对拍",
    // 批次四 · 总检报告（F170）
    reportLabTitle: "总检报告与证据包",
    reportRegression: "跨轮回归对比",
    reportFlaky: "抖动检测",
    reportEvidenceAudit: "证据完整性审计",
    reportExport: "导出 Markdown 报告",
    // 通用
    run: "运行",
    copy: "复制",
    copied: "已复制",
    // 批次五 · 素材管线（F156/F165）
    assetTitle: "素材管线（PNG 真产物）",
    assetSprites: "双倍率指针 sprite",
    assetBakeBudget: "开机烘帧字节预算",
    assetDowngrade: "降档建议",
    assetBytes: "字节",
    // 批次五 · 强调色阶梯（F151/F162）
    rampTitle: "强调色阶梯与色觉模拟",
    rampSlots: "语义槽位推荐",
    visionAudit: "状态色可辨识性（含三类色觉）",
    visionFix: "明度拉开建议",
    // 批次五 · 文案目录（十二查 13）
    copyAuditTitle: "空态/错误态/确认态目录审计",
    copyTriad: "三要素完整性",
    copyBanned: "禁词与标点",
    // 批次五 · 持久化（F161）
    persistTitle: "持久化模型（原子写/校验/迁移）",
    persistAtomic: "原子写两阶段",
    persistSeal: "信封校验和",
    persistMigrate: "迁移链",
    // 批次五 · 预览几何（F152）
    dirtyTitle: "预览场景脏区计算",
    dirtyRatio: "干净区占比",
    // 批次五 · 调度（F153/F163）
    schedTitle: "统一调度（公平份额）",
    schedMissed: "错过策略",
    schedWake: "唤醒恢复",
    // 批次五 · 使用排名（F167）
    usageTitle: "使用频率 EMA 排名",
    usageDecay: "半衰期衰减",
    usageExport: "隐私分组导出",
    // 批次五 · 速查表（F169）
    cheatTitle: "快捷键速查与走查脚本",
    cheatGrid: "打印栅格（三列均衡）",
    cheatOccupancy: "组合占用矩阵",
    cheatWalk: "纯键盘盲走脚本",
    // 批次五 · 档案合并（F161）
    mergeTitle: "档案三方合并",
    mergeAuto: "自动合并",
    mergeConflicts: "冲突（需裁决）",
    // 批次五 · 执法 runner（F170）
    runnerTitle: "域总检分片 runner",
    runnerShards: "分片",
    runnerIncremental: "断点续跑",
  },
  en: {
    studioTitle: "Personalization · Persona Studio",
    studioSubtitle: "E1-E8 · Theme/Wallpaper/Icons/Pointer/Sound/Start menu/Font/Motion — Iron rules: change anytime · revert anytime · presets+tweaks",
    close: "Close",
    navTheme: "Theme",
    navThemeTokens: "Token table",
    navThemePreview: "Live preview editor",
    navThemeAuto: "Auto dark switching",
    navThemeExceptions: "Per-app exceptions",
    navWallpaper: "Wallpaper",
    navIcons: "Icon packs",
    navPointer: "Pointer editor",
    navSound: "Sound mixer",
    navStart: "Start menu presets",
    navFont: "Font safety guard",
    navMotion: "Motion intensity preview",
    navArchive: "My profile",
    navWidgets: "Desktop widgets",
    navLock: "Lock screen",
    navBoot: "Boot animation",
    navIme: "IME skin",
    navCtx: "Context menu",
    navTaskbar: "Taskbar",
    navShortcuts: "Shortcuts",
    navVerdict: "Domain verdict",
    apply: "Apply",
    applied: "Applied",
    discard: "Discard changes",
    reset: "Reset defaults",
    save: "Save",
    saved: "Saved",
    on: "On",
    off: "Off",
    enabled: "Enabled",
    disabled: "Disabled",
    unappliedChanges: "You have unapplied changes",
    dirtyBannerHint: "Apply takes effect desktop-wide (300ms cross-fade, no restart); discard rolls back token-by-token with zero residue",
    hashVerified: "Hash-verified restoration (zero residue)",
    latencyOk: "Edit-preview latency within budget (≤100ms)",
    latencyOver: "Edit-preview latency over budget",
    previewScene: "Preview scene",
    sceneDesktop: "Desktop",
    sceneExplorer: "Explorer",
    sceneSettings: "Settings",
    restoreThisToken: "Restore this token default",
    coverage: "Coverage",
    tokensTitle: "Theme token table (F151)",
    tokensHint: "Five token classes: 24 colors / 6 spacing / 3 radii / 4 font sizes / motion 5 curves × 3 durations. Semantic edits hot-swap globally — a theme author only needs these 24 colors for a complete theme.",
    groupBg: "Backgrounds (3 layers)",
    groupFg: "Foreground",
    groupBrand: "Accent family",
    groupState: "State colors",
    groupLine: "Borders (3 tiers)",
    groupMisc: "Scrim/Hover/Focus/Selection",
    groupSpacing: "Spacing (6 tiers)",
    groupRadius: "Radius (3 tiers)",
    groupFont: "Font sizes (4 tiers)",
    groupMotion: "Motion (5 curves × 3 durations)",
    curve: "Curve",
    duration: "Duration",
    exportSchema: "Export JSON Schema",
    autoDarkTitle: "Auto dark switching (F153)",
    modeTimer: "By schedule",
    modeSunset: "By sunset/sunrise",
    darkAt: "Go dark at",
    lightAt: "Go light at",
    sunset: "Sunset",
    sunrise: "Sunrise",
    pairBinding: "Theme pair binding",
    nextSwitch: "Next switch",
    pauseToday: "Pause today (manual)",
    skipTonight: "Skip tonight",
    advanceToastTitle: "Theme switching soon",
    advanceNow: "Switch now",
    exceptionsTitle: "Per-app theme exceptions (F162)",
    exceptionsHint: "Max 10 items; exception apps keep their own dark/light/accent across global switches — commonality by default, individuality as privilege.",
    addException: "Add exception",
    exceptionMode: "Exception mode",
    accentOverride: "Accent override",
    tokenAware: "Token-aware",
    dailyWallTitle: "Daily wallpaper rotation (F154)",
    pool: "Image pool",
    changeAt: "Change at",
    rotateNow: "Rotate now",
    pinToday: "Pin today's pick",
    recentExclude: "7-day exclusion list",
    history: "History (30 days)",
    iconPackTitle: "Icon pack hot-swap (F155)",
    installPack: "Load sample pack",
    uninstallPack: "Restore official pack",
    rollbackPack: "Roll back one pack",
    coverageLabel: "Honest coverage",
    pointerTitle: "Pointer editor (F156)",
    hotspot: "Hotspot",
    hotspotUnset: "Hotspot unset (runs as (0,0))",
    scale: "Scale",
    exportScheme: "Export scheme (1x/2x sprites)",
    soundTitle: "Sound mixer (F157)",
    masterMute: "Mute all (master gate)",
    preview: "Preview",
    mutedGlobally: "Globally muted — preview is silent too (consistent gate semantics)",
    startTitle: "Start menu presets (F158)",
    saveCustom: "Save current as custom",
    elderMode: "Elder mode (large icons)",
    fullscreenMode: "Fullscreen start",
    fontTitle: "Font safety guard (F159)",
    missingRate: "Missing rate",
    verdictOk: "Pass",
    verdictWarn: "Yellow warning",
    verdictDanger: "Red discourage",
    forceApply: "I understand the missing-glyph impact, force apply",
    monospace: "Monospace",
    motionTitle: "Motion intensity preview (F160)",
    tierFull: "Full",
    tierReduced: "Reduced",
    tierOff: "Off",
    replay: "Replay trio",
    a11yNote: "Under Off, animations appear instantly; progress animations become explicit numbers (WP-207 accessibility note).",
    archiveTitle: "My profile (F161)",
    archiveName: "Profile name",
    exportArchive: "Export archive (vxtheme)",
    importArchive: "Import & restore",
    diffPreview: "Diff preview",
    sectionPick: "Section picks (a menu, not a bundle)",
    privacyHint: "Check phrases and names before export — private sentences may not be for sharing.",
    bytes: "bytes",
    widgetsTitle: "Desktop widgets (F163)",
    addWidget: "Add",
    opacity: "Opacity",
    clickThrough: "Click-through",
    lockTitle: "Lock screen (F164)",
    wallpaperFollow: "Follow desktop wallpaper",
    wallpaperIndependent: "Independent lock wallpaper",
    showBattery: "Status row · battery",
    showDate: "Status row · date",
    notifyPrivacy: "Notifications counted, never shown",
    bootTitle: "Boot animation (F165)",
    densityDense: "Dense (1200)",
    densityStandard: "Standard (600)",
    densityMinimal: "Minimal (200)",
    useWallpaperBackdrop: "Act-3 backdrop (wallpaper dimmed 65%)",
    bootInvariant: "Structure & duration immutable: 8.0s±0.2s (performance contract)",
    imeTitle: "IME skin (F166)",
    followTheme: "Follow theme",
    fontSize: "Font size (12-16px)",
    candidates: "Candidates",
    tryType: "Try: ni hao → 你好 — skin applies on next keystroke",
    ctxTitle: "Context menu (F167)",
    autoSort: "Auto-sort app items by usage",
    restoreDefault: "Restore defaults",
    lockedHint: "Delete/Rename/Properties are locked system items (no self-harm).",
    hiddenMore: "Hidden items remain fully under 'Show more options'",
    taskbarTitle: "Taskbar (F168)",
    iconSize: "Icon size",
    align: "Alignment",
    alignCenter: "Center",
    alignLeft: "Left",
    autoHide: "Auto-hide (reveal: cursor 200ms at bottom edge)",
    shortcutsTitle: "Shortcuts viewer (F169)",
    searchPlaceholder: "Search by name or key string…",
    rebind: "Rebind",
    recording: "Press new combo (Esc to cancel)",
    conflictWith: "Conflicts with",
    resetAll: "Restore all defaults",
    verdictTitle: "Domain verdict (F170)",
    verdictRun: "Run 19-item 3-step audit (mutate→effect→rollback)",
    verdictRunning: "Auditing…",
    verdictPass: "All green",
    verdictFail: "Red items found",
    stepMutate: "Mutate",
    stepEffect: "Effect",
    stepRollback: "Rollback",
    evidenceChain: "Evidence chain completeness",
    withinBudget: "Within 30-min budget",
    paletteTitle: "Wallpaper palette → token derivation",
    paletteExtract: "Extract palette",
    paletteDeriveDark: "Derive dark draft",
    paletteDeriveLight: "Derive light draft",
    paletteHarmony: "Wallpaper × theme harmony",
    paletteSwatches: "Dominant clusters",
    paletteDerived: "Derived draft (tweakable — not the final word)",
    paletteNoAccent: "Grayscale wallpaper — accent not fabricated (honest coverage)",
    solarTitle: "Sunrise/sunset (NOAA high-precision fallback)",
    solarAccuracy: "Delta vs Cooper fallback",
    solarEqTime: "Equation of time",
    solarDecl: "Solar declination",
    polarDay: "Polar day — light all day",
    polarNight: "Polar night — dark all day",
    preloadTitle: "Preload window planning",
    preloadPlanOk: "Preload scheduled — zero wait at swap time",
    preloadPlanMiss: "No idle window — reuse yesterday's wallpaper",
    atlasTitle: "Atlas packing plan",
    atlasPages: "Atlas pages",
    atlasOccupancy: "Occupancy",
    atlasOverflow: "Overflow (explicit)",
    atlasSwapBudget: "Swap budget breakdown",
    atlasWithinBudget: "Within <2s budget",
    cursorPhysicsTitle: "Pointer follow physics",
    cursorTrail: "Trail buffer",
    cursorSettled: "Settled (zero updates)",
    clickMachine: "Click state machine",
    hotspotTransform: "Precise hotspot transform",
    synthLabTitle: "PCM synthesis lab",
    synthRender: "Render & write WAV",
    synthPeak: "Peak",
    synthRms: "Loudness (RMS)",
    synthClipped: "Clipped samples",
    synthDuration: "Duration",
    widgetDataTitle: "Widget data engine",
    freshnessLive: "Live",
    freshnessStale: "Stale",
    freshnessFrozen: "Connection lost",
    freshnessNever: "No data yet",
    nextFetch: "Next fetch",
    jitterNote: "15s jitter window — widgets never refresh in lockstep (scheduler-storm immune)",
    lockComposerTitle: "Lock screen layers",
    lockFirstBeat: "First beat (<100ms visible)",
    unlockMachine: "Unlock state machine",
    unlockCooldown: "Cooling down",
    unlockRemaining: "Attempts left",
    blurSpec: "Backdrop blur spec",
    imeLabTitle: "Pinyin composition engine",
    imeSegments: "Syllable segmentation",
    imeCandidatesPage: "Candidates (page {p}/{n})",
    imeComposing: "Composing (shortcuts yielded)",
    ctxNavTitle: "Menu keyboard navigation",
    ctxTypeAhead: "Type-ahead (same letter cycles)",
    trayOverflowTitle: "Tray overflow layout",
    trayPinnedOverflow: "Pinned squeezed out (defect-grade signal)",
    chordLabTitle: "Chord matching engine",
    chordPending: "Sequence buffered (2nd chord within 1s)",
    chordTimeout: "Sequence timed out",
    chordConsistency: "Full-table consistency audit",
    reportLabTitle: "Verdict report & evidence",
    reportRegression: "Cross-run regression diff",
    reportFlaky: "Flakiness detection",
    reportEvidenceAudit: "Evidence completeness audit",
    reportExport: "Export Markdown report",
    run: "Run",
    copy: "Copy",
    copied: "Copied",
    assetTitle: "Asset pipeline (real PNG output)",
    assetSprites: "1x/2x pointer sprites",
    assetBakeBudget: "Boot bake byte budget",
    assetDowngrade: "Downgrade advice",
    assetBytes: "bytes",
    rampTitle: "Accent ramp & vision simulation",
    rampSlots: "Semantic slot suggestions",
    visionAudit: "State color distinction (incl. 3 CVD types)",
    visionFix: "Lightness-separation fix",
    copyAuditTitle: "Empty/error/confirm catalog audit",
    copyTriad: "Triad completeness",
    copyBanned: "Banned words & punctuation",
    persistTitle: "Persistence model (atomic/sealed/migrated)",
    persistAtomic: "Two-phase atomic write",
    persistSeal: "Envelope checksum",
    persistMigrate: "Migration chain",
    dirtyTitle: "Preview scene dirty rects",
    dirtyRatio: "Clean-area ratio",
    schedTitle: "Unified scheduler (fair share)",
    schedMissed: "Missed-run policy",
    schedWake: "Wake recovery",
    usageTitle: "Usage-frequency EMA ranking",
    usageDecay: "Half-life decay",
    usageExport: "Privacy-preserving export",
    cheatTitle: "Shortcut cheat sheet & walk script",
    cheatGrid: "Printable grid (3 balanced columns)",
    cheatOccupancy: "Combo occupancy matrix",
    cheatWalk: "Keyboard-only blind walk script",
    mergeTitle: "Archive three-way merge",
    mergeAuto: "Auto-merged",
    mergeConflicts: "Conflicts (need decision)",
    runnerTitle: "Domain audit shard runner",
    runnerShards: "Shards",
    runnerIncremental: "Incremental re-run",
  },
} as const;
